### PR TITLE
Media manager JS cleanup. Media Manager now uses e107.behaviors.

### PR DESCRIPTION
**Pull request by lonalore**

### CODE REVIEW

**Comment by CaMer0n** [comment]
Thank you!! Tested with Bbcode and TinyMce inline image as well as imagepicker() and filepicker() ?

**Comment by lonalore** [comment]
Yeah, I tested it!

(works) - BBCode Area (without tinymce4)
(works) - BBCode Area (with tinymce4)
(works) - ImagePicker (tested on news)
(works) - IconPicker (tested on sitlinks)
(works) - FilePicker (tested on a page-custom field)

**Comment by lonalore** [comment]
And I also tested it with SimpleMDE editor. :) It worked.

**Comment by CaMer0n** [comment]
Excellent! 👍

**Pull request merged**
