### PR TITLE
Update lan_notify.php

### PR DESCRIPTION
**Pull request by yesszus**

### CODE REVIEW

**Comment by yesszus** [comment]
@CaMer0n pls review this.

**Comment by Moc** [comment]
Please give him a little more than 24 hours :)

**Comment by yesszus** [comment]
Ok

**Comment by Moc** [comment]
Idea, not sure: should we create a LAN_TEST in English.php for general use?

**Comment by yesszus** [comment]
Ok, work this and changed.

**Comment by CaMer0n** [comment]
lan_users.php has "Test [x]" .  It would be better to stick with that, and place it in lan_admin.php for use by notify.php. I don't see the need for "Test" on the front end.

**Comment by yesszus** [comment]
Changed.

**Pull request closed without merging**
