### PR TITLE
Delete Account Optional

### PR DESCRIPTION
**Pull request by LaocheXe**
Added option in admin area to allow users to delete their account or not. In reference to #3945

Basically adds an option in Admin Area > Users > Options > Allow members to delete account? (yesno)
Hides the Delete button on usersettings.php (using shortcode)

### CODE REVIEW

**Comment by Moc** [comment]
This will be a new preference right? In that case it also needs to be added to the default installation XML file

**Comment by LaocheXe** [comment]
@Moc what file do I need to edit? I checked out the default_install.xml and notice none of the user options are listed there.

**Comment by Moc** [comment]
That's indeed the file. It's weird that some of them are missing. Not all though, for example `memberlist_access` is there. 

@CaMer0n What are your thoughts on this?

**Comment by CaMer0n** [comment]
@Moc Do you have a list of the preferences which are missing?

**Comment by LaocheXe** [comment]
@CaMer0n want me to add those  to the install.xml as well, or is this good to go?

**Comment by LaocheXe** [comment]
I'm going to close this pull request and apply a newer one with updated install.xml

**Pull request closed without merging**
