### PR TITLE
Sept16

### PR DESCRIPTION
**Pull request by tgtje**
Text to LAN's

since system core files change rapidly here are a few txt to lan's

### CODE REVIEW

**Comment by CaMer0n** [comment]
Thank you! It's almost usable as is. However some LANs contain paths (eg. e_MEDIA) and {SHORTCODES}. These need to be replaced with [x] and then $tp->lanVars() used to replace them within the context of the script using them.

**Comment by Moc** [comment]
@tgtje Something like this is what is needed: 

```php
define("LAN_CHMOD_FOLDER", "The folder [x] is not writable. Please correct before proceeding.");
```

And then:
```php
$message = $tp->lanVars(LAN_CHMOD_FOLDER, e_MEDIA); 
$mes->addWarning($message);
```


@CaMer0n  Are you referring to CUSLAN_80 with a shortcode? If yes, would this be solution? 

```php
define("CUSLAN_80", "Will be listed in the Menu-Manager under this name or may be called using [x] in your theme. Must use ASCII characters only and be all lowercase.");
```  	

```php
		'menu_name' 		=> array('title'=> CUSLAN_64, 		'tab' => 2,	'type' => 'text', 		'width' => 'auto','nolist'=>true, "help"=> $tp->lanVars(CUSLAN_80, "{CMENU=name}"),

**Comment by tgtje** [comment]
Shortcode ? 
CUSLAN_80
Will be listed in the Menu-Manager under this name or may be called using {CMENU=name} in your theme   (CMENU=  is pure textual (no linkage) = Create Page/MEnu ..TAB MENU > Menu Name > hover text....

**Comment by CaMer0n** [comment]
@Moc Thanks. Yes, that looks right. (as long as it is defined in the init() method)

**Pull request closed without merging**
