### PR TITLE
Created LAN to replace hardcoded txt as described in issue #1141

### PR DESCRIPTION
**Pull request by tgtje**
files involved : plug/page/e_search php;  lang/English/lan_search php

### CODE REVIEW

**Comment by Moc** [comment]
I'm pretty sure that only the English.php files are supposed to have the LAN_NAME structure. All other files still follow the LAN_XXX_## structure, such as LAN_SEARCH_001. 

@CaMer0n Correct?

**Comment by CaMer0n** [comment]
@Moc, yes, that's correct. English.php and lan_admin.php are the only files which should contain the format LAN_(DESCRIPTION). Also, @tgtje, in this particular case, the LAN should be defined in page/English_global.php - not lan_search.php , as it is being called by:  e107_plugins/***page***/e_search.php.  You can use Plugin Builder's language checking utility in this case too.

**Comment by tgtje** [comment]
Aha, learned something new. 
About page/English_global.php > does not exist
 went ahead and did some stuff > would this be the way to?? .. sorry but an image explains it better ( i hope : bit piled)
Still again the question remains ; how the LAN should carry how and what.. (Note : there is NO language folder and no lang files in PAGE plugin)

runall

**Comment by CaMer0n** [comment]
@tgtje Excellent! Just a small modification to make.  forgot to mention that English_global.php is the other file which has it's own format. 

    LAN_PLUGIN_(PLUGIN_FOLDER)_(UNIQUE_DESCRIPTION)

**Comment by tgtje** [comment]
Changed the global file to use LAN_PLUGIN_PAGE_BOCHAPT (thinking this would be the proper one now) and yes it appears as above imgage in the plugin builder check.

However : out of my league now :  Using this method (forget to check? its final routine yesterday),
the LAN is displayed on search page NOT the defined txt. This (imo) tells me there is something else to do to get it going...(calling the def txt from within lang folder) (tried at least 20 combos> still LAN).....( wonder if this decommented line holds the issue // Removes the need for search_parser.php, search_advanced.php and in most cases search language files.)

Reverting back to LAN_SEARCH_203  (instead of descr from comment Moc) it displays fine, but plugin builder tells it is missing... ( i can trick the builder by adding that line ALSO in global, but that is not to be the solution).

**Comment by CaMer0n** [comment]
You'll want to check in the preference editor to see that 'page' is in 'lan_global_list'. 
Running a plugin scan might also help.

**Comment by tgtje** [comment]
The plugin rescan did the trick and added auto an example file ? (Testing 1 step at a time) (not noticed before).
Thank you. 
Again something to remember to look...Thought v1 was already well thought about, the new stuff in v2 keeps me amazed (lets call them 'hidden' features ) Great job!...have to mention it..
Back to work : testchanges to commit..

**Comment by CaMer0n** [comment]
thank you @tgtje Positive feedback is always appreciated! :+1:

**Pull request closed without merging**
