### PR TITLE
Update theme_shortcodes.php

### PR DESCRIPTION
**Pull request by mcpeace-maw**
Update font icons.

### CODE REVIEW

**Comment by CaMer0n** [comment]
Is this a repeat of the previous pull-request?

**Comment by mcpeace-maw** [comment]
No, it is first time I make changes in this file. The old file have 4 old font awesome icons and I updated the icons to version 4.3 of font awesome, the same version like in theme.php (bootstrap theme) pull .

**Comment by CaMer0n** [comment]
Looks the same as this?
https://github.com/e107inc/e107/blob/master/e107_themes/bootstrap/theme_shortcodes.php

**Comment by mcpeace-maw** [comment]
Yes.

**Pull request closed without merging**
