### PR TITLE
Replaced ADMSLAN_4 with LAN_CONTINUE - attempt 2

### PR DESCRIPTION
**Pull request by MikeyGMT**
First tiny step to contribute to the coding of e107

I have replace ADMSLAN_4 in administrator.php with LAN_CONTINUE from English.php and commented ADMSLAN_4 out in lan_administrator.php

### CODE REVIEW

**Comment by CaMer0n** [comment]
Thanks for all this work! btw. Please always test the files you changed. Downloads admin area ceased to function after this commit.

**Comment by CaMer0n** [comment]
Also, if you have used any lan_admin.php definitions on a front-end template, they will not work.

**Comment by MikeyGMT** [comment]
Oh wow - I only asked for the first commit I made to be pulled. I wasn't aware that all my work would be pulled. I was going to test the other work at some point before pulling it. Learning along the way. :) Hope I have not broken much more!

**Comment by CaMer0n** [comment]
I fixed a few things, but if you could test install.php and the few other files that were affected, that would be great.

**Comment by MikeyGMT** [comment]
Hi Cameron

Tested OK & documented process.

Am going to replace Admin Username in the prompts in Administrator details
page - i.e. just Username.

On the last page - prompt to delete install.php is missing.

Will test further affected features next.

Mike

**Comment by CaMer0n** [comment]
Okay, thank you! :+1:

**Comment by MikeyGMT** [comment]
Aha it lost the powerpoint I attached. Mail you direct

**Comment by CaMer0n** [comment]
@MikeyGMT Enhancements and fixes committed. Please see #6 for details.

**Pull request merged**
