### PR TITLE
Update bb_p.php

### PR DESCRIPTION
**Pull request by sudakk**
Tested on News & Pages

### CODE REVIEW

**Comment by Moc** [comment]
Fixes #3977

**Comment by Moc** [comment]
@sudakk Please submit these cpage fixes as new pull-request. Now there are merged into the bb_p.php PR. You have to create a new branch in your repository, then you can submit it as a new PR.

**Comment by sudakk** [comment]
@Moc Sorry I understand I did it wrong way... but I don't understand how revert changes.

**Comment by Moc** [comment]
No problem. You need to 'revert' the commit by adding another commit undoing the changes. You can use Github desktop for this for example. If you want, I can also close this pull-request so you can create a new one. 

Thank you for your contributions! 👍

**Comment by sudakk** [comment]
Thank you! Next try will be better I hope

**Pull request closed without merging**
