### PR TITLE
More Duplicate LANS #6 in Submit News, Cron, Mailout

### PR DESCRIPTION
**Pull request by MikeyGMT**
More Duplicate LANS #6 in Submit News, Cron, Mailout

### CODE REVIEW

**Comment by MikeyGMT** [comment]
Testing

Submit News
image

**Comment by MikeyGMT** [comment]
Cron - git cron - warning, my server does not allow git commands. Just showing page not broken.
image

**Comment by MikeyGMT** [comment]
Mailout LAN_MAILOUT_42 not used. 
image

**Comment by CaMer0n** [comment]
Excellent. Thank you!

**Pull request merged**
