### PR TITLE
Merge pull request #8 from e107inc/master

### PR DESCRIPTION
**Pull request by rica-carv**
.

### CODE REVIEW

**Comment by CaMer0n** [comment]
@rica-carv Please use git rebase to avoid 'merge' entries. ;-)

**Comment by rica-carv** [comment]
@CaMer0n git rebase? Sorry, but i don't use the github desktop, i simply use the web site, so i can't rebase (wich is kind of stupid, not to have on the website the same options that there's on the desktop command line...)...

**Comment by CaMer0n** [comment]
@rica-carv I'm using TortoiseGit, but yeah, that is strange that they don't have the option online. 
Some info for anyone else reading this: http://stevenharman.net/git-pull-with-automatic-rebase

**Comment by Jimmi08** [comment]
Ok, I don't know (or better never use, I have vague idea what it does) rebase but I use this solution for cleaning my fork:
http://stackoverflow.com/questions/9646167/clean-up-a-fork-and-restart-it-from-the-upstream
Each my pull request is in separate branch always done from master. 
Maybe this helps somebody.

**Comment by rica-carv** [comment]
Good tutorials, but unfortunatelly, all has to be donne via github desktop , and unfortunatelly, i can't use it....
Maybe github is not for the moving developing, like me, that just uses a USB pen.....

So, until a online option is available to rebase, i'll have to do it with this stupid way....... grrrrrrrrrrrr

**Comment by CaMer0n** [comment]
@rica-carv Perhaps this is worth looking into? https://github.com/sheabunge/GitPortable

**Comment by rica-carv** [comment]
@CaMer0n Well, i'm currently doing this: 

- [](http://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository)
- [](http://www.hpique.com/2013/09/updating-a-fork-directly-from-github/)

I find quite "stupid" to have a local copy on my pc (or usb pen) of my github fork, just to make a rebase (wich by the way includes a lot of commands....)....
Really, github has to grow up and be more user friendly, indeed....[](url)

**Comment by CaMer0n** [comment]
@rica-carv How do you test your code changes before you send the pull-request?

**Comment by rica-carv** [comment]
@CaMer0n On a always updated fresh setup of e107, on my usb development server....
After i check if the changes work, i use copy & paste and make the changes on my fork, and issue a commit...
I know it's not the way to go, but github in far from being coerent and user friendly....

Furthermore, since the testing site i have installed on the pen has a few more files than the master e107 repositore (or my fork) here on github, wouldn't my fork be updated with those files, when i issue a commit from my local site?
For instance, removed install.php and added created files, like e107_config.php, etc????
And if i use the testing site also to develop plugins, they would also be pushed to my fork, right?
Simply speaking, would be a real mess....

**Comment by Moc** [comment]
@rica-carv I understand your frustration and I believe that the majority of this is caused by your specific workflow (in this case using a portable USB). It's always easier to have a full workstation available (be it a fixed desktop or portable one such as a laptop or tablet) since it allows for more things to run such as applications (e.g. Github for Windows/Mac or TortoiseGit). 

I agree that Git is complicated. Github (the website) tries to simplify this by offering limited options through the webinterface and allowing more advanced processes through their windows/mac application and Tortoisegit (external tool). 

As for your question regarding e107_config.php and the cache files, these are added into the .gitignore file (so they are ignored by Git). The install.php file is still required to be there, but you can enable a dev setting in either the config file or htaccess to remove the the 'install.php presence warning' on the frontend of e107. 

Using something like Github for Windows/Mac or TortoiseGit gives you far more insight into what you are commiting and will take care of a lot of your frustrations (e.g. showing the whole file as changed instead of specific lines, and having plugin or theme files commited which you don't want to commit). 

Hope this helps ;)

**Comment by rica-carv** [comment]
@Moc I can see that a setup workstation or laptop is always better, but currently i can't do that, simply because i'm always on the move. For instance, now i'm working on a XP laptop, and later i can be working on a Vista desktop or 10 laptop, so i can't really depend on a specific laptop setup for that. I rather prefer to have a smaller usb pen all setup for on the go development, that i can plug on any machine and work imediatly with it......

I'll try to do some more resarch regarding all this git stuff, but i rather spend 90% of my free time coding and 10% updating code on github than the opossite.... :laughing: 

Thank you all for all the help, i'll give it one more try...

**Pull request closed without merging**
