### PR TITLE
Change proposal of forum description

### PR DESCRIPTION
**Pull request by rica-carv**
Changed proposal to parse embeded shortcodes on the forum description, if any present....

### CODE REVIEW

**Comment by CaMer0n** [comment]
A description is not a title. Normally 'BODY' should be used.

**Comment by rica-carv** [comment]
@CaMer0n Err, so i got to correct it, right? :smile:

**Comment by CaMer0n** [comment]
@rica-carv Yes :+1:  Thank you!!
btw. I'm slowly trying to replace all the TRUE/FALSE with true/false (lowercase)

**Comment by rica-carv** [comment]
@CaMer0n Like this #1622 ??

**Comment by CaMer0n** [comment]
Yes, exactly. But it's a minor thing, and not worth another commit.

**Comment by rica-carv** [comment]
@CaMer0n Well, anyway i added the commit before your reply... :smiley: 
Should i close it?

**Comment by CaMer0n** [comment]
Yeah, thanks.

**Pull request merged**
