### PR TITLE
Text To LANS #6 infopanel

### PR DESCRIPTION
**Pull request by MikeyGMT**
Text To LANS #6 infopanel

### CODE REVIEW

**Comment by MikeyGMT** [comment]
Testing 
image

**Comment by Moc** [comment]
@CaMer0n Would it be an idea to have the months (January, February, etc.) defined in the English common LAN?

**Comment by MikeyGMT** [comment]
I thought that too... but was reluctant to do so. I can always revisit.

**Comment by MikeyGMT** [comment]
I'm actually thinking there's a way to call a formatted date month only and then no translation needed.

**Comment by MikeyGMT** [comment]
OK ... so testing this (not committed yet)

```
			$data['labels'] 	= array(strftime("%B",mktime(0,0,0,01,01,16)), //"January",
							strftime("%B",mktime(0,0,0,02,01,16)), //"February",
							strftime("%B",mktime(0,0,0,03,01,16)), //"March",
							strftime("%B",mktime(0,0,0,04,01,16)), //"April",
							strftime("%B",mktime(0,0,0,05,01,16)), //"May",
							strftime("%B",mktime(0,0,0,06,01,16)), //"June",
							strftime("%B",mktime(0,0,0,07,01,16))  //"July"
							);
```
Returns the correct months in English. Switch e107 admin to Welsh ... still returns English Month Names. 

Hmmm downloading another lan and testing with that.

**Comment by MikeyGMT** [comment]
Tested with NL, PT, same result ... 

OK so in the line above I set 
`setlocale(LC_ALL,"hu_HU.UTF8");`
The months have come out as the intended. 
So does this mean the site language is not observed in all scripts?

**Comment by MikeyGMT** [comment]
Aha ok ... So I was switching Language with the multilan switcher. 

Setting it with the core language settings worked. 

Sadly php doesn't seem to understand Welsh though :(

**Comment by MikeyGMT** [comment]
Sorted ... I had in the top of Welsh.php 

setlocale(LC_ALL, 'cym.UTF-8', 'cym.utf8', 'cym.utf8', 'cym');

This seems to work better. Although I am not sure what the different parameter are (or should be). 
setlocale(LC_ALL, 'cy_GB.utf8','cym.utf8', 'cym.utf8',  'cym');

**Comment by MikeyGMT** [comment]
Retesting 
image

**Pull request closed without merging**
