### PR TITLE
Text To Lans - FAQs #6

### PR DESCRIPTION
**Pull request by MikeyGMT**
Text to Lans - FAQs #6
FYI new Tab under Prefs > Display : makes the prefs neater on the page.

### CODE REVIEW

**Comment by MikeyGMT** [comment]
Testing - and see new prefs > display tab

image

image

**Comment by CaMer0n** [comment]
Thanks @MikeyGMT! I feel as if "Display" prefs should be under "General" and everything about "Submit a question" in a separate tab. What do you think? 

Also, I believe the description of the prefs in the "FAQs" and "Categories" tabs have become so generic that it's difficult to know what they are for.  Both tabs represent admin perms.

**Comment by MikeyGMT** [comment]
Hi Cameron
I'll take a look and rework. The aim is to make the prefs fit on a page
without the need to scroll, just seems neater, but I take your point it
could do with some tidying further.
Thanks
Mike

**Comment by MikeyGMT** [comment]
Have put the display stuff under 1st General tab.
Have used LAN_FAQS_ASK_A_QUESTION and moved to English_Global, made it the second tab. 
image

Was thinking one "Manage" tab then underneath have a sub-tab for Questions and for Categories - but not sure how to do the Sub-Tab - for example:

```
Manage
|_ Questions
| |_Create
| |_Edit
| |_Delete
|
|_Categories
| |_Create
| |_Edit
| |_Delete
```
In a next iteration, perhaps add help section. 
What do you think?

**Comment by CaMer0n** [comment]
It's an improvement. Thank you @MikeyGMT !

**Comment by yesszus** [comment]
Parse error: syntax error, unexpected '"."' (T_CONSTANT_ENCAPSED_STRING) in e107_plugins\faqs\faqs_shortcodes.php on line 301

https://github.com/e107inc/e107/pull/2511/files#diff-3c24c1cb0ec0ae4290ca40036dcec897R301

**Correct solution:**  questionCharLimit.LAN_FAQS_CHAR_LIMIT."

**Comment by yesszus** [comment]
**Lan crons not work in email!** 

`define("LANA_FAQ_CRON_1", "Unanswered Questions Report");
define("LANA_FAQ_CRON_2", "Mails a report of unanswered questions to [x].");
define("LANA_FAQ_CRON_3", "[x] Unanswered Questions at [y]");
define("LANA_FAQ_CRON_4", "Please login to your site to review and answer these questions using the link below.");
define("LANA_FAQ_CRON_5", "The [x] most recent questions are displayed below.");
define("LANA_FAQ_CRON_6", "[x] Unanswered Question as of [y].");`

Moved to: lan_admin.php tested and work this.
Added phrase: define("LAN_CLICK_HERE", "CLICK HERE");  in lan_admin.php

**Comment by CaMer0n** [comment]
This is still incorrect, even if it doesn't cause an error.  
`'subject' => $tp->lanVars(LANA_FAQ_CRON_6, count($count) ,date('d-M-Y')),`
```
Please see the comments on the lanVars function: 
/**
	 * Generic variable translator for LAN definitions.
	 * @param $lan - string LAN
	 * @param string | array $vals - either a single value, which will replace '[x]' or an array with key=>value pairs.
	 * @example $tp->lanVars("My name is [x] and I own a [y]", array('x'=>"John", 'y'=>"Cat"));
	 * @example $tp->lanVars("My name is [x] and I own a [y]", array("John","Cat"));
	 * @return string
	 */
	function lanVars($lan, $vals, $bold=false)
	{

```

**Comment by yesszus** [comment]
This correct: [https://github.com/e107inc/e107/blob/master/e107_plugins/faqs/e_cron.php#L78](url)
Work this without errors.

**Comment by CaMer0n** [comment]
Yes, because I fixed it. ;-)

**Pull request merged**
