### PR TITLE
Issue #3151 add an e_end to plugin class

### PR DESCRIPTION
**Pull request by oudoken**
Hi There,
Based on #3151 i've modified these files and seems to work ok, it will be an usefull addition to e107 for all the things related in output buffering (start and end) or maybe i haven't find a better option?

### CODE REVIEW

**Comment by CaMer0n** [comment]
@oudoken Nice work! How about calling it, e_buffer or possibly e_output ? Some of the code you copied from is a little outdated, I will update it so you can work from that.

**Comment by oudoken** [comment]
@CaMer0n Hi Cameron, sure well e_end was really the mean of it... so i think it can be e_buffer or e_ouput (btw i prefer the last one).
In fact calling it e_end can motivate to rename e_module in e_start... But i leave the naming convention To You guys! 👍 
I'm already working on a V2.0 plugin that use phpFastCache for producing static html's cache files and it's working ok.

**Comment by CaMer0n** [comment]
Thanks! Yeah, having e_end would be strange without an e_begin or e_start. e_module isn't quite the start either.. , so, let's go with **e_output.php**. If you can make the change and test it, I'll commit your pull-request. Thank you.

**Comment by oudoken** [comment]
@CaMer0n Ok perfect lemme make the change Thanks a Lot Cameron

**Comment by oudoken** [comment]
@CaMer0n Hi Cameron ok modified e_end in e_output also written some more in comments to explain a little more Thanks Rob 👍

**Comment by CaMer0n** [comment]
Great! Thank you @oudoken ! :+1:

**Comment by oudoken** [comment]
Hi @CaMer0n Thanks 👍 
If You have time check 
https://github.com/oudoken/static_cache
It's an example implementing this pull request
Thanks Kind Regards
Rob

**Comment by CaMer0n** [comment]
Nice work Rob ! :+1:

**Comment by CaMer0n** [comment]
Yes, JS manager.  
```
/**
	 * Minify JS/CSS for output
	 * @param string $minify
	 * @param string $type (js|css)
	 * @return string
	 */
	private function compress($minify, $type = 'js' )
    {
```
ie.  `$compressed = e107::getJs()->compress($code, 'css');`

**Pull request merged**
