### PR TITLE
Issue #2894

### PR DESCRIPTION
**Pull request by lonalore**
#2894

### CODE REVIEW

**Comment by rica-carv** [comment]
Excuse me for this, but wouldn't it be more straight forward and cleaner to have those variables (`$perPage, $amount, $size`) removed and use the already defined constant `PLUGIN_ITEMS_PER_PAGE`?

I just can't see the benefit of reusing a constant as multiple variables, for me it's ankward....

Sorry, just my 2 cents......

**Comment by lonalore** [comment]
Good point! :+1: This was just a quick fix. Feel free to reroll it.

**Comment by LaocheXe** [comment]
Would it also be possible to add a time error for people who try to download to many plugins at once? Currently still getting the 
[#] Bad Link
Unable to continue

**Comment by CaMer0n** [comment]
Great! Thank you @lonalore

**Pull request merged**
