### PR TITLE
Rewrited JS code to use e107.behaviors. Behavior to enable Smooth Scr…

### PR DESCRIPTION
**Pull request by lonalore**
Rewrited JS code to use e107.behaviors. 
Behavior to enable Smooth Scrolling if URL has a fragment.

### CODE REVIEW

**Comment by lonalore** [comment]
I think we would provide ability for the user to customize "Smooth Scrolling". For example: enable/disable it, to change duration for animation, and most importantly, to set a top-offset in the case theme has a fixed top-navigation bar.

I thought that we would create additional tab called "Global preferences" in theme-manager:
kepernyokep - 2016-02-04 - 09 44 42

We can send these settings to front-end using e107::js('settings', ...);

... so users can customize the JS behavior without overriding the JS code.

**Comment by Moc** [comment]
Great addition. If this gets merged in, please document it so people know how to use it! :)

**Comment by lonalore** [comment]
The "global" Smooth Scrolling was @CaMer0n's idea. :)
Here is a documentation about JavaScript Behaviors: https://github.com/e107inc/e107/issues/1259
(If grammar is not correct, please fix it...)

**Comment by Moc** [comment]
Perfect, thanks!

**Comment by CaMer0n** [comment]
@lonalore Great work! However I'm a bit nervous about such a large change to the front-end javascript, at this time. I believe this pull-request should be merged AFTER 2.0.1 so it can be tested in different environments for some weeks/months before being in the following official release. A few extra lines for the scroll animation would have been fine, but this is a rewrite of the entire file - like your subject says.  :-)

**Comment by lonalore** [comment]
Thank You! :) Anyway, almost the whole code is unchanged inside the behaviors, I just copied them from the "document ready" event. But okey, it can wait for the next release, because as I noticed, the "comment" section of the code is heavily buggy. The "Edit" button does nothing, The "Vote Up/Down" and "Reply" buttons can be used only once. So it needs of thorough testing and rewriting.

**Comment by CaMer0n** [comment]
Thanks. Only one vote per use was intended. ;-) The 'edit' button seems to be failing though.

**Comment by lonalore** [comment]
Ohh, so after voting (or a wrong click), user cannot change it? :P :D

**Comment by lonalore** [comment]
I created a new pull-request only with the "Smooth Scrolling". #1338

**Comment by CaMer0n** [comment]
Thank you!, will commit it now.

**Pull request closed without merging**
