### PR TITLE
#6 User Settings Lans 

### PR DESCRIPTION
**Pull request by MikeyGMT**
Removing duplication, converted text to userlans and common lans. Had to move LAN_SAVE and LAN_SAVED to English.php as Usersettings on front pages. See further details in the commits.

### CODE REVIEW

**Comment by MikeyGMT** [comment]
Oh no - what has git done! 
I don't want all these duplicates in here!
Before starting to work after some rejections, I did 
git reset -- hard 
Now it has included all the tooing an frowing of cleaning up after. Grrr. 
Closing this one!

**Comment by MikeyGMT** [comment]
It seems insane. Are we to delete our entire local repo and recreate a new fork after any commit? 
[Reaches for the gin ! ]

**Comment by Moc** [comment]
Nope, just a new branch for each separate pull request. Doing the command you did is not recommended. 

You may want to look into Github for windows. That's easier to understand.

**Comment by MikeyGMT** [comment]
Thanks Moc. Yes I am using desktop.
Last pull was rejected, hence was trying to get my copy back to current state of e107/master. 
FYI - I used that command on good advice : ) honest.
git rebase - did something messy too. 
I'm going camping for a few days now ...  I'll think about it after that. 
:)

**Comment by MikeyGMT** [comment]
@Moc Do you branch from e107inc/master or from self/last_branch_after_pull_request?

**Comment by Moc** [comment]
@MikeyGMT I think I don't understand your question completely. Simply put, to submit a pull-request:
- Fork the e107 project
- Commit the changed to your local fork 
- Submit a pull-request. 

Now, I advise to work with different branches on your local fork to avoid certain issues. 
- Fork, create new branch, commit changes to new branch, submit a pull-request from fork/new-branch to e107/master.

**Comment by rica-carv** [comment]
And always keep your forked master branch up to date with the original e107 master branch...

**Comment by Moc** [comment]
Yes @rica-carv, that's right :) This can be easily done in Github for Windows/Mac (they have pull & push nicely integrated).

**Comment by rica-carv** [comment]
@Moc  I don't use the github desktop (portability & performance issues), i always use the website, and i can keep my fork updated with e107 master branch. Just have to do a "reverse" commit.... :wink:

**Pull request closed without merging**
