### PR TITLE
Update e107_languages/English/admin/lan_admin.php 

### PR DESCRIPTION
**Pull request by yesszus**
Some corrections.

### CODE REVIEW

**Comment by yesszus** [comment]
Renamed.

**Comment by CaMer0n** [comment]
Thank you @yesszus !! Just a little change, let's use LAN_UI_FILTER for this particular set that applies to the filter dropdown. (Just like we do for LAN_UI_BATCH )

**Comment by yesszus** [comment]
Changed.

**Comment by CaMer0n** [comment]
Thank you! I will make some changes.

**Pull request merged**
