### PR TITLE
Enable wrapper to have parseable shortcodes

### PR DESCRIPTION
**Pull request by rica-carv**
Enable wrapper to have parseable shortcodes, issue #1616

### CODE REVIEW

**Comment by CaMer0n** [comment]
It appears you're trying to parse every shortcode twice. I don't think this is a good idea.

**Comment by rica-carv** [comment]
Corrected to only parse wrapper, and some minor code changes

**Comment by CaMer0n** [comment]
I believe it would good for performance to check if `$pre` and `$post` have a shortcode in it before attempting to run `preg_replace_callback('#\{([A-Z][^\x02]*?\S)\}#', array(&$this, 'doCode'), $pre/$post) `   what do you think?

**Comment by rica-carv** [comment]
Something like this?
```
$match='#\{([A-Z][^\x02]*?\S)\}#';

preg_match($match, $pre/$post)
?
preg_replace_callback($match, array(&$this, 'doCode'), $pre/$post)
:
$pre/$post;
```

**Comment by CaMer0n** [comment]
Thanks. I just committed something similar. Please test.

**Comment by rica-carv** [comment]
@CaMer0n Thanks, it works.
No we can get rid of those hardcoded HTML strings inside shortcodes (i hope...)

**Comment by rica-carv** [comment]
@CaMer0n Sorry, but it seems it works only with shortcodes (new or overriden) from the theme, not with shortcodes from the plugins...
I've tested it with custom forum shortcodes in a theme (ie: `$SC_WRAPPER['THREADSX'] = "<a href='{FORUMTHEMESHORTCODE}'>{---}</a>";`), and it works, but the shortcodes form the plugin doesn't (ie: `$SC_WRAPPER['THREADSX'] = "<a href='{FORUMNAME}'>{---}</a>";`)...

**Comment by CaMer0n** [comment]
Please try now. There's a commented-out test on line 139 of forum_template.php

**Comment by rica-carv** [comment]
@CaMer0n Thanks, now it works as intended....
Proceeding with HTML cleanup... :smile:

**Pull request closed without merging**
