### PR TITLE
Update admin_style.css

### PR DESCRIPTION
**Pull request by mcpeace-maw**
Responsive fix for middle icon buttons.

### CODE REVIEW

**Comment by mcpeace-maw** [comment]
On my test site bootstrap3 admin works well with these changes.

**Comment by CaMer0n** [comment]
@mcpeace-maw Thanks! Will commit and test here. Cheers.

**Comment by mcpeace-maw** [comment]
The only thing that is not responsive now is the top right icon navigation bar on admin layout of bootstrap3.

**Comment by CaMer0n** [comment]
@mcpeace-maw I think these are the 2 remaining issues now (but probably a single issue affecting both). Missing right-margin: 

bootstrap3-missing-right-margin


infopanel-alignment-issue

**Comment by mcpeace-maw** [comment]
What you see is the effect of the row div that I added in #right-panel div.
The warning wrapper div need span12 in bootstrap and col-md-12 in bootstrap 3. That will solve that issue.

**Comment by CaMer0n** [comment]
@mcpeace-maw actually, the right-margin is gone from every page of the admin area.

**Comment by CaMer0n** [comment]
@mcpeace-maw I see what's going on, will fix and commit.

**Comment by mcpeace-maw** [comment]
All divs that are direct child of the added row (inside #right-panel div) need col-md-12 or other size to compensate the negative margin added by that row div.

**Pull request merged**
