### PR TITLE
Update theme.php

### PR DESCRIPTION
**Pull request by mcpeace-maw**
OK, added font awesome 4.3. Now the font icons are OK in forum. The theme need some css adjusts too if use old bootstrap. Maybe custom forum template files with old bootstrap classes in the theme folder?

### CODE REVIEW

**Comment by CaMer0n** [comment]
Yes, I believe the old bootstrap2 will need a custom forum template.

**Comment by Moc** [comment]
@cameron: isn't e107 phasing out BS2? Why not use BS3 only? It's been stable for months and to maintain two different versions seems like a waste of resources.

**Comment by CaMer0n** [comment]
I would love to drop BS2. In fact, if I could get the admin area working with BS3, I would remove BS2 from the core. It's a huge job though.

**Comment by mcpeace-maw** [comment]
I just finished to update this theme (bootstrap core theme) to bootstrap 3.3.5 and theme upload not working on e107.org site. If someone want to test it, send me an email.

**Comment by CaMer0n** [comment]
Can you please email me your theme so I can test the upload on e107.org?

**Pull request merged**
