### PR TITLE
Issue #2756 - Ability to override site_path. Done: "TODO create direc…

### PR DESCRIPTION
**Pull request by lonalore**
…tories which dont exist."

### CODE REVIEW

**Comment by lonalore** [comment]
@CaMer0n please review this. Thank you!
Related issue: #2756

**Comment by lonalore** [comment]
I found an issue with this. So please ignore my last comment. :) I'll fix it soon.

**Comment by lonalore** [comment]
Okay, done! :)

**Comment by CaMer0n** [comment]
Thank you @lonalore ! If you haven't already, could you please perform a fresh install using your changes? Changes like this have been known to break installation in the past.

**Comment by lonalore** [comment]
Installation was successful, and the [hash] directories were created in **e_MEDIA** and **e_SYSTEM**.

kepernyokep_2017-08-07_22-39-52

**Pull request merged**
