### PR TITLE
Fix for datepicker.

### PR DESCRIPTION
**Pull request by lonalore**
According to this: https://github.com/e107inc/e107/commit/82beb3385c099d1b202674e5daa3475ef2bc9c81#commitcomment-17752290

### CODE REVIEW

**Comment by lonalore** [comment]
It would be advisable to use PHP Unit for e107, and write tests to avoid "surprises" like this. :D

**Comment by CaMer0n** [comment]
@lonalore I have my own test scripts that I run. Please paste your exact datepicker() variables so I can add it to the test. Thanks. You want a unix timestamp returned or a string?

**Comment by lonalore** [comment]
I want a string as return value. :)
```php
$varDateStart = array(
	'label'   => LAN_RESERVATION_FRONT_09,
	'name'    => 'date_start',
	'value'   => varset($_POST['date_start'], $day),
	'id'      => $form->name2id('date_start'),
	'options' => array(
		'format'   => varset($prefs['date_format'], '%d/%m/%Y'),
		'firstDay' => varset($prefs['week_start'], 1),
		'size'     => 20,
		'required' => true,
		'return'   => 'string',
	),
);

$form->datepicker($varDateStart['name'], $varDateStart['value'], $varDateStart['options']);
```
where `$_POST['date_start']` is a formatted date string (e.g. with format: %d/%m/%Y)

thank you!

**Comment by rica-carv** [comment]
@lonalore can't you use the [`convert_date` function](https://github.com/e107inc/e107/blob/048ab169dae624416a27972168a12a0b8bdc9509/e107_handlers/date_handler.php#L145)???

**Comment by lonalore** [comment]
The aim would be this:

```php
// Input value: 06/06/2016
// In the widget the value should be: 06/06/2016
// Submitted value should be: 06/06/2016
$vars = array(
	'name'    => 'example',
	'value'   => '06/06/2016',
	'options' => array(
		'format'   => '%d/%m/%Y',
		'return'   => 'string',
	),
);
$form->datepicker($vars['name'], $vars['value'], $vars['options']);


// Input value: 1465171200
// In the widget the value should be: 06/06/2016
// Submitted value should be: 1465171200
$vars = array(
	'name'    => 'example',
	'value'   => 1465171200, // Timestamp input!
	'options' => array(
		'format'   => '%d/%m/%Y',
		// 'return'   => 'string',
	),
);
$form->datepicker($vars['name'], $vars['value'], $vars['options']);


// Input value: 1465171200
// In the widget the value should be: 06/06/2016
// Submitted value should be: 06/06/2016
$vars = array(
	'name'    => 'example',
	'value'   => 1465171200, // Timestamp input!
	'options' => array(
		'format'   => '%d/%m/%Y',
		'return'   => 'string', // Need to string as returned value!
	),
);
$form->datepicker($vars['name'], $vars['value'], $vars['options']);
```

**Comment by CaMer0n** [comment]
Thank you!! :+1:

**Comment by CaMer0n** [comment]
@lonalore Have you tried editing a news item and checking the date field? I see a unix datestamp displayed. How about you?

**Comment by Jimmi08** [comment]
if this helps, this line is problem - in datepicker():
`$useUnix    = (isset($options['return']) && ($options['return'] === 'string')) ? 'false' : 'true';`

for news is result true, should be false.

**Comment by lonalore** [comment]
This should fix it. Need to convert default value to string in both cases.

**Pull request merged**
