### PR TITLE
Fix for datepicker(). Tested!

### PR DESCRIPTION
**Pull request by lonalore**
Issue #1687 
Issue #1694 

I did some tests while drinking my morning coffee because this issue bothered me... here is my test page: http://demo.lonalore.hu/e107v2/e107_plugins/_blank/_blank.php

Before submit:
kepernyokep - 2016-06-09 - 10 13 28

After submit:
kepernyokep - 2016-06-09 - 10 14 05

The point is that, we have to set timestamp (initial value) in the hidden field in the case where timestamp is selected.

### CODE REVIEW

**Comment by lonalore** [comment]
Furthermore, I recommend moving javascript code into a separated file, and using javascript behaviors, because datepicker is not initialized on form elements are load via Ajax. If you allow me, I will move JS code into a JS behavior.

**Comment by lonalore** [comment]
@CaMer0n can you merge this final fix? Thank you! :)

**Comment by CaMer0n** [comment]
Thanks for the code. Unfortunately it broke some functionality. Try editing a 'string' value directly in the text-input field and hit enter, it should update the hidden value, but it no longer does.

**Comment by lonalore** [comment]
Thank you! This should fix it!

**Pull request merged**
