### PR TITLE
Forum fvars & tvars removal

### PR DESCRIPTION
**Pull request by rica-carv**
Forum fvars & tvars removal from files forum_viewtopic.php & forum_viewforum.php.
There's also a few code changes & cleanup for previous submit #1677 (forum.php & forum_shortcodes.php)

All changes were tested in Bootstrap3 & Jayya themes, and are correctly rendering, but might need aditional testing for more "heavy" forums....

### CODE REVIEW

**Comment by CaMer0n** [comment]
Thank you @rica-carv ! Before I merge this, could you tell me which aspects of the changes you have tested? eg. have you tried quick-reply, thread tracking, moving threads, deleting threads etc. etc.

**Comment by rica-carv** [comment]
Err, @CaMer0n no, i haven't tested it throughtly, i just tested its output on bootstrap3 & jayya themes, and all was fine....
All thread activity i haven't tested it....

**Comment by rica-carv** [comment]
@CaMer0n Quick reply works, standard does not, also thread activities (tracking, move, delete, etc.) doesn't work....
Guess got to get back to drawing board.... :pencil2: :triangular_ruler:

**Comment by rica-carv** [comment]
@CaMer0n Editing and moderator bugs fixed, when i test it, all worked....

**Pull request merged**
