### PR TITLE
Banner Lans to Generic Terms #6

### PR DESCRIPTION
**Pull request by MikeyGMT**
Replace duplicates with common terms in Banner Plugin.
Created this TODO term also LAN_DEFAULT_TABLE_DATA - for use in other
plugins too.

### CODE REVIEW

**Comment by MikeyGMT** [comment]
Testing 
image

image


image

image

image

Note - should this be save not close after configuration changes made...?

image

**Comment by MikeyGMT** [comment]
Let me know if it is incorrect to comment this menu option out. My bad, happy to uncomment. 

I was going to shorten to "Configure Menu" so it fits in the left column, but saw that it's no longer done here... 

e107_plugins/banner/admin_banner.php 

`//	'main/menu'			=> array('caption'=> BNRLAN_36, 'perm' => 'P'), //NOW CONFIGURED IN MENU MGR`

**Comment by MikeyGMT** [comment]
Reverted and shortened to fit. 
image

**Comment by CaMer0n** [comment]
I think commented-out is better.  Maybe we need to work on the help file to explain where one can configure specific instances via Menu-Manager.

**Comment by MikeyGMT** [comment]
Testing - this is the first stab at help - I think it can grow. 

image

Also I have added the filename and a TODO message in CORE_IMAGE.PHP which drives file inspector.

**Comment by MikeyGMT** [comment]
File inspector entry (Result Core File Unchecked)
image

**Pull request merged**
