### PR TITLE
Added a "how to" for contributing to e107

### PR DESCRIPTION
**Pull request by SimSync**
Added a .md file to explain in a few steps, how to contribute by using forks, branches, push and pulls and how to rebase at the end ...
At least that's the way i do it ...

### CODE REVIEW

**Comment by rica-carv** [comment]
Installing git is not the only way to contribute.
You can also do everything from here (github.com), without installing anything....

**Comment by SimSync** [comment]
You are right. But than you are not able to test and debug your changes. So the risk of typos or other sources of bugs is quite high.
I used it myself too for very small changes.
But I wouldn't recommend it if you're not 120% sure of what you do.

**Comment by rica-carv** [comment]
@SimSync Not quite. I use the github site all the time, without any need to install git, and i ALWAYS test my chansges in localhost server, before submitting them, so there's almost 0% chance of bugs or typos from me...

**Comment by Moc** [comment]
I suggest changing this filename to CONTRIBUTING in order to take advantage of the Github features as explained here: https://blog.github.com/2012-09-17-contributing-guidelines/

**Pull request merged**
