### PR TITLE
PM Cleanup & menu icons

### PR DESCRIPTION
**Pull request by rica-carv**
Constant PM_SEND_LINK cleanup (why define again a existing constant?)

Icons reverted from PNG to Glyphs

Todo's:
- Can PNG's be safelly deleted?
- PM_OUTBOX_ICON is a candidate to Fontawesome stacked icon, since there's no native fontawesome outbox icon...
- NEWPM_ANIMATION is a candidate to Fontawesome animated icon, since there's no native fontawesome animated new message icon...

### CODE REVIEW

**Comment by rica-carv** [comment]
@CaMer0n That `define('PM_SEND_LINK', LAN_PLUGIN_PM_NEW);` has to get out from the template, because teh pm_menu code itself currently relies on that, and if for some reason on a custo theme tempalte that define is not there, the pm_menu will not render correctly the pm_send_link...

**Comment by rica-carv** [comment]
Added customization inside template for the send_pm button....

**Comment by CaMer0n** [comment]
@rica-carv I agree, I don't like the constants for the icons. However, we'd need to maintain backward compatibility.

**Comment by rica-carv** [comment]
pm_menu_template.php is new, there was no such template before 2.1.5.....
So, no backwards compatibility problem...

**Comment by rica-carv** [comment]
Some loose ends:
-     Can PNG's be safelly deleted?
-     PM_OUTBOX_ICON is a candidate to Fontawesome stacked icon, since there's no native fontawesome outbox icon...
-     NEWPM_ANIMATION is a candidate to Fontawesome animated icon, since there's no native fontawesome animated new message icon...

**Comment by CaMer0n** [comment]
How will this work on an old theme which doesn't use fontawesome?

**Comment by rica-carv** [comment]
@CaMer0n Once more, the old themes never used the pm_menu_template, since it's new now.
On previous PM plugin versions, the menu was all hardcoded inside the pm_menu.php file itself, so i figure that the PNG's where only used there.
I've taken care on only "messing" with it so i can mantain backwards compatibility, that's why i've made those questions, since i can's see that being used elsewhere on the PM plugin, but...

**Comment by CaMer0n** [comment]
Sure thing. Thank you!

**Comment by rica-carv** [comment]
So:
- Can PNG's be safelly deleted?
- PM_OUTBOX_ICON is a candidate to Fontawesome stacked icon, since there's no native fontawesome outbox icon...
- NEWPM_ANIMATION is a candidate to Fontawesome animated icon, since there's no native fontawesome animated new message icon...
?

**Comment by CaMer0n** [comment]
What happens if the theme doesn't use fontawesome?

**Pull request merged**
