### PR TITLE
#4597: Remove TinyMCE postprocessing over AJAX

### LINKED ISSUE #4597: user signature problem with national characters
## Bug Description
Not sure what is going and if this can be my mistake.

tinymce4 on user signature 

Editing looks correctly 
image

Saving in database is problem:
`[html]Nikdy nehovor, že niečo nejde, pretože sa vždy n&amp;aacute;jde blbec, čo to urob&amp;iacute;.&amp;nbsp;[/html]`
 
User profile looks like this:
image

News (no issue) with the same string looks in the editor the same way:
image
But it is saved in database this way:
`[html]<p>Nikdy nehovor, že niečo nejde, pretože sa vždy nájde blbec, čo to urobí.&nbsp;</p>[/html]`
 
Text is:  `Nikdy nehovor, že niečo nejde, pretože sa vždy nájde blbec, čo to urobí.`

Thanks

### PR DESCRIPTION
**Pull request by Deltik**
### Motivation and Context
@Jimmi08 reported in #4597 that TinyMCE WYSIWYG textareas outside of AdminUI were getting its contents double-HTML entity-encoded.

While investigating the cause, I found that `e107_plugins/tinymce4/plugins/e107/parser.php` was performing a dance of client-side server text mutations, leading to poor performance of TinyMCE for text changes like pasting into the textarea.

### Description
The server will "toWYSIWYG" the bbarea textarea before the form
is rendered and "toDB" it after the form is submitted instead of on
every change to the text inside the TinyMCE editor.

This should greatly improve performance while editing text inside
TinyMCE.

The solution isn't the best-looking, but in order to get the tinymce4
plugin addon `e_parse` the appropriate information about which fields
were bbarea textareas, I added a new input field specifically for
`e_form::bbarea()`, namely `"__meta_type_{$name}"`, where `{$name}` is
the form field name of the bbarea textarea.
`validatorClass::validateFields()` now passes along the field name
`$parm['field']` to `e_parse::toDB()`.

`e107_plugins/tinymce4/plugins/e107/parser.php` has been replaced with a
compatability layer, as all its behavior is now supplied by
`tinymce4_parse` from `e107_plugins/tinymce4/e_parse.php`.

Additionally, a separate bug in `e_parse::toDB()` prevented the
`e_parse` `toDB` addon hooks from running: The method was bailing out
before the hooks if the `$mod` was not `"model"`, but a comment says
that hooks should not mess with prefs, not anything else.  To fix this
bug, the `$mod` check is now looking for `"pReFs"` instead.

Finally, this change fixes #4597 by decoding the HTML entities that
would have been present in the bbarea textarea.  This logic is towards
the top of `tinymce4_parse::toDB()`.

### How Has This Been Tested?
Unit test `tinymce4_parseTest` replaces `e107TinyMceParserTest`.

Manual acceptance test you can try:
1. Copy some text.
2. Hold down [Ctrl]+[v] in a TinyMCE textarea.
3. Notice how it's much faster to paste text now than before.

### Types of Changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist

- [x] My code adheres to the e107 [code style standard](https://github.com/e107inc/e107/wiki/e107-Coding-Standard).
- [x] I have read the [**contributing** document](https://github.com/e107inc/e107/blob/master/.github/CONTRIBUTING.md).
- [x] I have added [tests](https://github.com/e107inc/e107/tree/master/e107_tests) to cover my changes.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by Deltik** [comment]
Okay, plugin version incremented: https://github.com/e107inc/e107/compare/f10025baef92695f228f3e674295289b3e429a3b..f74b26b75ef82bcbf7e501b5b167dd67355596d7

**Comment by CaMer0n** [comment]
Thank you! Tested again. 

When I inserted an image (4.png), it didn't convert the img tag back to bbcode as intended and didn't wrap it in `[html]` tags. 

### Expected news_body table data: 

```
[html]<p>[img title=4]{e_MEDIA_IMAGE}2021-10/4.png[/img]</p>[/html]
```

### Actual news_body table data: 
```
<p><img class=&quot;img-rounded rounded bbcode bbcode-img&quot; src=&quot;/e107v2/thumb.php?src=e_MEDIA_IMAGE%2F2021-10%2F4.png&amp;w=400&amp;h=0&quot; alt=&quot;4&quot; title=&quot;4&quot; width=&quot;400&quot;></p>
```

**Comment by Deltik** [comment]
https://github.com/e107inc/e107/blob/236248503accbabacd03c764f371c5c8030145b3/usersettings.php#L393-L393 is stripping HTML out of the input.  I don't really understand why that code exists because [the actual input sanitization happens after it](https://github.com/e107inc/e107/blob/236248503accbabacd03c764f371c5c8030145b3/usersettings.php#L455-L455).

**Comment by Deltik** [comment]
Regarding the `e107_admin/newspost.php` thing, it looks like `e_admin_controller_ui::_manageSubmit()` doesn't do form validation like on the frontend.

Stack:
```
admin_ui.php:4847, news_admin_ui->_manageSubmit()
admin_ui.php:6439, news_admin_ui->EditSubmitTrigger()
admin_ui.php:2229, news_admin_ui->dispatchObserver()
admin_ui.php:1333, news_admin->runObservers()
admin_ui.php:1105, news_admin->__construct()
newspost.php:1620, {main}()
```

Compare with `usersettings.php`:
```
e_parse.php:103, tinymce4_parse->toDB()
e107_class.php:2962, e107::callMethod()
e_parse_class.php:618, e_parse->toDB()
validator_class.php:1262, validatorClass::validateFields()
usersettings.php:437, usersettings_front->init()
usersettings.php:1138, {main}()
```

So this is frustratingly inconsistent.  The two ways to save data don't have anything in common.

**Comment by CaMer0n** [comment]
Thanks @Deltik Will try it out! 
btw. You can use ```defset('LAN_PLUGIN_FORUM_POSTS') ```

**Comment by Deltik** [comment]
@CaMer0n:

> Keep in mind that TinyMce is a replacement for virtually any textarea, in any plugin, old or new, so best to do any string conversion prior to submitting the form.

The `e_parse` addon seemed like the perfect hook for this task.  Anything else I could think of requires an extra round-trip request to get the BBCode conversion, and even still, that relies on the client to send back good data again.  Keeping the processing server-side in the `e_parse` addon avoids an extra request.

> The [html] tags are there at least. 
> 
> ```[html]<p></p>[/html]```

Is there a problem with the BBCode now?  When I tried adding an image using the media picker, I got this in the database:

```
[html]<p>Lorem ipsum dolor sit amet, no meis semper dicunt est, petentium eloquentiam quo ne. <strong>At vero facer eam.</strong></p>
<p>[img title=Horse]{e_MEDIA_IMAGE}2021-10/horse.jpg[/img]</p>[/html]
```

**Comment by Deltik** [comment]
Here's what I got when I created a welcome message:

```html
[html]<p><strong>Welcome</strong> <em>Message</em></p>
<p>[img title=Preview Frontend]{e_THEME}bootstrap3/preview_frontend.png[/img]</p>[/html]
```

I noticed that yours has some extra attributes like `title` and `width`.  Could those have prevented the `[img][/img]` BBCode tags from appearing?

**Comment by CaMer0n** [comment]
@Deltik https://github.com/e107inc/e107/commit/b91b1c36b0c1f50cd687df6b0187e8647b302690 fixed the original issue with minimal changes to the existing code, thereby avoiding unforeseen issues that could occur with the many changes included in the pull-request.  May be revisited after release of v2.3.1 when more time can be allotted to testing the changes with different configurations.

**Pull request closed without merging**
