### PR TITLE
Issue #6: Remove and optimize (hardcoded) LANS

### PR DESCRIPTION
**Pull request by lonalore**
It was a rainy day... :P

### CODE REVIEW

**Comment by CaMer0n** [comment]
Wow, thank you. Btw. We shouldn't add LANs for debug information. It just makes the language files larger than they need to be. (And they are already incredibly large)

**Comment by lonalore** [comment]
Hmm okey! I understand! :) I remove them in my next commit, then I will continue to remove hardcoded LANs.

**Comment by CaMer0n** [comment]
Excellent! Also, please always check lan_admin.php for an existing term before creating a new one. eg. LAN_PREFS, LAN_AUTHOR etc. (There's been much duplication in the past, causing unnecessary work for translations. ) :+1:

**Comment by lonalore** [comment]
The strings in $mes->addInfo() are debug messages?

**Comment by CaMer0n** [comment]
No, not unless it is wrapped in an E107_DEBUG_LEVEL "if" statement.

**Comment by oxigeno2** [comment]
I found duplicity:
  in file - lan_language.php

define ('LANG_LAN_116 "" Please verify your language files (' Verify ') then try again. ");
define ('LANG_LAN_118 "" Please verify your language files (' Verify ') then try again. ");

**Comment by lonalore** [comment]
Thank You! I removed duplication.

**Comment by oxigeno2** [comment]
Duplication or specify in text width / height  :-)
in file - admin/lan_image.php

define ('IMALAN_76 "" Avatar images will be constrained to these dimensions (in pixels)");
define ('IMALAN_78 "" Avatar images will be constrained to these dimensions (in pixels)");

**Comment by oxigeno2** [comment]
Duplication or change the text in help
in file - admin/lan_image.php

define ('IMALAN_88 "" Watermark Position");
define ('IMALAN_89 "" Watermark Position");

**Comment by lonalore** [comment]
Yes, and I found more, of course I removed them.

**Pull request merged**
