### PR TITLE
Update admin_template.php

### PR DESCRIPTION
**Pull request by mcpeace-maw**
Removed inutile classes, added a row class div inside right-panel div = responsive fix.

### CODE REVIEW

**Comment by CaMer0n** [comment]
@mcpeace-maw  Thank you! If it's no trouble, please start your commit description with "Issue #1138" (meaning, bootstrap3 work)

**Comment by CaMer0n** [comment]
@mcpeace-maw These changes have broken the bootstrap2 infopanels.

**Comment by mcpeace-maw** [comment]
I'll take a look at bootstrap theme now.

**Comment by CaMer0n** [comment]
It's fixed. Committing. @mcpeace-maw

**Pull request merged**
