### PR TITLE
Update landingzero theme

### PR DESCRIPTION
**Pull request by yesszus**
Add lang codes.

### CODE REVIEW

**Comment by yesszus** [comment]
Can not apply for admin languages in theme_config.php, only bootstrap3 English_admin.php.

Add `e107::lan('theme', 'admin',true);` in theme_config.php and doesn't not work for me.

**Comment by yesszus** [comment]
@CaMer0n pls review theme_config.php.

**Comment by CaMer0n** [comment]
try adding this to theme_config:

    function __construct()
    {
      e107::lan('theme', 'admin',true); 
    }

...does it help?

**Comment by yesszus** [comment]
Sorry, not work me this.

**Comment by CaMer0n** [comment]
I will look into it.

**Pull request merged**
