### PR TITLE
Removal of vars from forum.php

### PR DESCRIPTION
**Pull request by rica-carv**
Remove of vars from forum.php, changed forum_template.php and added forum_shortcodes.php shortcode file...
Please test, on my side it's working...

Todo:
- Add wrapper funcionality
- Remove hardcoded html from shortcodes to template
- After testing, remove all comment out lines...

### CODE REVIEW

**Comment by CaMer0n** [comment]
Thank you! @rica-carv  There's still some things to fix before I can merge.. see https://codeclimate.com/github/e107inc/e107/pull/1662

**Comment by CaMer0n** [comment]
Need to discuss in chatroom before merge.

**Comment by rica-carv** [comment]
Ok


Às 18:07 de 21-05-2016, Cameron escreveu:
>
> Need to discuss in chatroom before merge.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/e107inc/e107/pull/1662#issuecomment-220789213>
>



---
Este e-mail foi verificado em termos de vírus pelo software antivírus Avast.
https://www.avast.com/antivirus

**Comment by rica-carv** [comment]
@CaMer0n Just rewriten all my modified code as we agreed on gitter....

**Comment by CaMer0n** [comment]
Thanks! forum.php was modified 6 days ago. Did you merge those changes in as well?

**Comment by rica-carv** [comment]
@CaMer0n If i recall correctly, that change was #1614 no?
If that's the case, i already put that shortcode on the forum_shortcode file: https://github.com/e107inc/e107/pull/1662/files#diff-ed39d88b3efafaf24cac81de0132cc65R320

**Comment by rica-carv** [comment]
@CaMer0n Sorry, now i noticed that wasn't that change, but anyway, the change made 6 days ago only removed an empty line and added another empty line: https://github.com/e107inc/e107/commit/ec36f1dc877e206e89c02b61a875f5f8b50dd20d#diff-0512db550fc71428d49ad783d01482d8R327

**Pull request closed without merging**
