### PR TITLE
A few minor fixes and corrections...

### PR DESCRIPTION
**Pull request by lonalore**
…the posts/page limit is set to 20.

### CODE REVIEW

**Comment by CaMer0n** [comment]
@lonalore this looks like more than just pagination. Please provide before and after screenshots of all the template changes. (including mobile phone layout) thank you!.

**Comment by lonalore** [comment]
### Forum List page (before centering) - Dekstop
Screenshot 1

### Forum List page (after centering) - Dekstop
Screenshot 1

### Forum List page (before centering) - Mobile
Screenshot 1

### Forum List page (after centering) - Mobile
Screenshot 1

### Pagination + Action button + Reply form (before my changes) - Dekstop
Screenshot 1

### Pagination + Action button + Reply form (after my changes) - Dekstop
Screenshot 1

### Pagination + Action button + Reply form (before my changes) - Mobile
Screenshot 1

### Pagination + Action button + Reply form (after my changes) - Mobile
Screenshot 1

**Comment by Moc** [comment]
:+1:

**Comment by lonalore** [comment]
Is there any progress about merging these fixes and changes? o.O

**Comment by lonalore** [comment]
So it will be good? o.O

**Comment by Moc** [comment]
It looks excellent to me but @CaMer0n is the one who is merging pull-requests :)

**Comment by CaMer0n** [comment]
All good! :+1:  Sorry for the delay.

**Comment by lonalore** [comment]
It's okay, I understand. Thank You! :)

**Pull request merged**
