### PR TITLE
Social Plugin Steam

### PR DESCRIPTION
**Pull request by LaocheXe**
Added XURL_STEAM in social plugin, allows Steam Page

### CODE REVIEW

**Comment by LaocheXe** [comment]
This is to add in Social Plugin Steam Page XURL

**Comment by CaMer0n** [comment]
Thanks. Other than class2.php I can't see what you changed. Each script looks like a re-write.. see here: 
https://github.com/e107inc/e107/pull/2698/files

**Comment by LaocheXe** [comment]
@CaMer0n The files I changed was class2.php and social/admin_config.php - didnt remove, just added XURL

**Comment by CaMer0n** [comment]
Thanks. As you can see, it says that 24 files were modified. You might want to re-sync and submit another PR.

**Pull request closed without merging**
