### PR TITLE
gsitemap addon for news plugin

### PR DESCRIPTION
**Pull request by Jimmi08**

### CODE REVIEW

**Comment by CaMer0n** [comment]
Excellent work @Jimmi08 ! :+1:

**Comment by Jimmi08** [comment]
Thanks. But now I need a solution how to get this out from core and replace by custom plugin.  There is no plugin name in that array :)

**Comment by CaMer0n** [comment]
@Jimmi08 What would the custom plugin do differently?

**Comment by Jimmi08** [comment]
I put example here: 

https://github.com/e107inc/e107/issues/3344

**Pull request merged**
