### PR TITLE
Library Manager UI.

### PR DESCRIPTION
**Pull request by lonalore**
I created a small UI for Library Manager in order  to be able to see installed third-party libraries.
kepernyokep - 2016-06-20 - 11 01 11

**TODO:**
- Determine a permission code to use instead of "Z" (Plugin Manager), if its necessary...
- Need to find and change icon (now it uses Plugin Manager's icon):

kepernyokep - 2016-06-20 - 11 01 24

@CaMer0n Can you help me completing TODO list?

### CODE REVIEW

**Comment by rica-carv** [comment]
@lonalore Some sugestions for your icon:
app-win-settings-icon  filesystem-socket-icon  script_code_red  disconnect-icon-55980  action-run-icon  app-kservices-icon  app-software-icon

**Comment by lonalore** [comment]
@rica-carv thank you! Where did you find these icons? On e107's credit page I saw that e107 uses 'Nuvolo Icons'. These icons are Nuvolo icons?

kepernyokep_2016-06-20_19-27-12

**Comment by rica-carv** [comment]
@lonalore No, the one i find are not from **Nuvola** icons... Maybe one or other are, but i did a search on google for a icon similar to the one in the admin area, and these poped up....
Nuvola (not nuvolo) icons are [here](http://findicons.com/pack/2118/nuvola), but there's a few icons on e107 that are no from this set, they might came from a diferent icon set....

**Comment by rica-carv** [comment]
@lonalore Some icons, from Nuvola icon pack:
misc  configure  connect_established  laptop_charge  shellscript  kdisknav  designer  kig  kcontrol  kservices  kfig  kcmsystem  attach

**Comment by CaMer0n** [comment]
Looks great. I'm just not convinced that it deserves an entirely new section of the admin area. There is not much to "Manage" so it doesn't quite seem appropriate to be in this category. It may be more appropriate to add it to this page: /e107_admin/prefs.php#nav-core-prefs-javascript  and rename the page "Libraries" (instead of Javascript Framework)

**Comment by lonalore** [comment]
Done!

kepernyokep - 2016-06-21 - 10 23 00

**Comment by CaMer0n** [comment]
Excellent! Thank you! :+1:

**Pull request merged**
