### PR TITLE
#4692 email.php on forum

### LINKED ISSUE #4692: email.php on forum is not working
## Bug Description
 
check e107.nl
image

When you click on the option Email, nothing happens.

I noticed this thanks to Google search console with this error:
```
Redirect error
for URL 
```
https://www.e107sk.com/email.php?plugin:forum.38

Because I wasn't sure if this forum exists (you don't see IDs anywhere) - I checked e107.nl 
 
## Expected Behavior
There is an issue 
`https://github.com/e107inc/e107/issues/4453`
so there could be some changes...   

It is not the same issue, this one is about 404 results for google searching. 

I don't have any email client installed (like Outlook, Thunderbird or something), but I should get at least some info box about not access or not working or something... 

and email.php should be by default added into robots.txt..

Thanks

### PR DESCRIPTION
**Pull request by Jimmi08**
CLOSES #4692 

**Description**
if the user doesn't have the right to send an email (only members have this by default), the email option was still displayed for them. But it did nothing (looked like not working) because redirection to the homepage in email.php itself. 

**Changes**:
- fixed email.php redirection 
- added checks for email rights - to post options and email icon too

**Notes** 
- there is another issue related directly to email icon functionality, so for now, only a check was added.  A better solution is to display a disabled button like the post reply option does. But this is another issue. 
 
- there is another issue related to post options (or will be). so for now, just check was added. 

There should be rules that `{POSTOPTIONS}` is used for posts but {`EMAILITEM}` and `{PRINTITEM}` should be used primarily for thread (or works on both places}

### CODE REVIEW

**Comment by CaMer0n** [comment]
@Jimmi08 Please check your code formatting. Which editor are you using? Does it work with **.editorconfig** ?

**Comment by Jimmi08** [comment]
> @Jimmi08 Please check your code formatting. Which editor are you using? Does it work with **.editorconfig** ?

PSPAD but I can use Visual Studio Code  (you can't past the code directly to e107 tinymce editor, it adds spans to the code itself, so I always forgot to check it) 

But I just tried 2 formatter there, no change with the code above. 
I need to know what formatter to use (PHP CS FIXER or PHP FORMATTER or other) and their settings (f.e. .php_cs)  Somebody else has to use it too, it is free and good. 

By the way, I couldn't find a link to e107 rules for formatting. I know it exists. 

I have other issues fixed already but they are more complicated and this will be always the problem. Maybe you just could use the idea and write it yourself in needed way. There is no hurry. I am sure it would be save your time. 
Sorry this mess again.

**Comment by CaMer0n** [comment]
@Jimmi08 Please go here, it will tell you which editors support **.editorconfig** already, or have a plugin for download. 
https://editorconfig.org/#pre-installed
After that is set up, it typically should load https://raw.githubusercontent.com/e107inc/e107/master/.editorconfig automatically.

**Comment by Jimmi08** [comment]
@CaMer0n thanks, I don't see any difference but I did it manually. 

Maybe is better to show you the full code (issue #4705}

image


{EMAILITEM} is probably legacy shortcode, the same functionality is in postoptions. 
What is needed is to get it outside posts, the button for the thread.  Solution above works for both scenarios.

You don't have access:  (disabled buttons, red cursor like with reply button, no URL for bots  )
image

You have access (normal button)
image

**Pull request closed without merging**
