### PR TITLE
Add external avatar file check for missing files

### PR DESCRIPTION
**Pull request by rica-carv**
### Motivation and Context
External avatar files, when missing, give this output:
Screenshot 2024-04-27 at 11-37-17 SelosPT
Screenshot 2024-04-27 at 11-36-55 Gestor de plugins - Instalado - Área do administrador SelosPT

### Description
Added code to revert to default avatar image, when external file is missing, output like this:
Screenshot 2024-04-27 at 12-52-09 SelosPT
Screenshot 2024-04-27 at 12-51-40 Língua - Área do administrador SelosPT

### How Has This Been Tested?
Tested in e107 v2.3.3 clean install,
Output tested in admin area and in the front end (pics above)

### Types of Changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist
- [x] My code adheres to the e107 [code style standard](https://github.com/e107inc/e107/wiki/e107-Coding-Standard).
- [ ] I have read the [**contributing** document](https://github.com/e107inc/e107/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/e107inc/e107/tree/master/e107_tests) to cover my changes.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Comment by CaMer0n** [comment]
Thanks for this. Maybe I'm misreading it, but the **file_exists()** function in PHP does not work with remote URLs, so I'm not sure how this is working for you. ?

**Comment by rica-carv** [comment]
> Thanks for this. Maybe I'm misreading it, but the **file_exists()** function in PHP does not work with remote URLs, so I'm not sure how this is working for you. ?

Sorry, im using localhost, so forgot it's a remote url. Just changed file_exists for fopen for remote url checking

**Comment by rica-carv** [comment]
There's something wrong, because the generic avatar is still not rendered on the front end, and i narrow it down to this line in `e_parse_clas.php`: 			`$url = $this->createConstants($url, 'mix');`

The issue is that the createConstants method renders as the src of avatar image `%7Be_IMAGE%7Dgeneric%2Fblank_avatar.jpg` when it should be `e107_images/generic/blank_avatar.jpg`....

**Comment by rica-carv** [comment]
Sorry, closing again and reopening another one because i had changes in my main code, not in a branch. Sorry

**Pull request closed without merging**
