### PR TITLE
Feature Request: Forum Link Icon/Image #1635

### PR DESCRIPTION
**Pull request by chory**
Lets show an image in the list of forums

### CODE REVIEW

**Comment by rica-carv** [comment]
Wow, why do you delete all .htaccess data?
And i see a lot of "custom" code there (in bootstrap3 theme templates...)
Furthermore, you should update your own branch to e107 head, you're 603 commits behind....

**Comment by CaMer0n** [comment]
Closing due to deletion of e107.htaccess - unable to merge in its current state.

**Comment by chory** [comment]
I deleted what?
_Only modified 8 files_
e107_plugins\forum\forum_admin.php
e107_plugins\forum\forum_class.php
e107_plugins\forum\forum_sql.php
e107_plugins\forum\languages\English\English_admin.php
e107_plugins\forum\shortcodes\batch\forum_shortcodes.php
_And I created the file e107_themes\bootstrap3\templates\forum\forum_template.php that did not exist._

**Furthermore, you should update your own branch to e107 head, you're 603 commits behind....**
I do not understand, I downloaded the latest version directly from Github

**Comment by Moc** [comment]
@chory Did you try Github Desktop? https://desktop.github.com

**Comment by rica-carv** [comment]
@chory And please check if this issue isn't already solved with latest github files...
Thanks

**Comment by chory** [comment]
@Moc Yes, I'm using it, but I'm very lost
@rica-carv I do not see that it's solved
thank you for answering me

**Comment by rica-carv** [comment]
@chory Sorry, i was thinking it was another request.
Now i see what's the purpose.
I've already proposed the changes sometimes ago in #1635 ...

**Comment by chory** [comment]
I created a Gist https://gist.github.com/chory/fd467660a32553ce77b4d396012e4cc4.
I hope this time if you can see it without me breaking anything.  :fearful:

**Comment by rica-carv** [comment]
@chory [English] If you need help setting up a branch a issue a commit to master e107 branch, i'll be glad to help. Just drop me a line in private in gitter.im. That gist is not going to help too much, you really need to send a pull request...
[Español] Se necessitas ayuda para hacer eso dentro de github, dejame una mensaje en gitter.im, y intentaré ayudarte. El gist que hiciste no vay a ayudar mucho, tienes mesmo que hacer un "pull" para esos cambios haceren parte de e107...

**Pull request closed without merging**
