### PR TITLE
#1608 Removed harcoded language

### PR DESCRIPTION
**Pull request by rica-carv**
Removed harcoded language.

Will try to see a solution tio the templating issue...

### CODE REVIEW

**Comment by rica-carv** [comment]
The templantig issue will not be easy....
Moving the HTML from the function to the template won't do, since if `{VIEWABLE_BY}` is empty, it will display all the divs around it anyway.
That's why i understand that the HTML still is inside the function, since there, if the string is empty, it will return nothing...

But this shortcode could work in template if somehow i could figure out a way to make shortcode wrappers work in forum_viewforum.php file.....

**Comment by rica-carv** [comment]
As suggested here, i've managed to temporarly workaround the templating of the `{VIEWABLE_BY}` shortcode, but since i still got some issues, it's only a temporary workaround....
Please check the changes proposal here (also commented by me):
- [forum_viewforum.php](https://github.com/rica-carv/e107/commit/5dad8e2f94ea3582b60e6daf897e8890cc588613)
- [view_shortcodes.php](https://github.com/rica-carv/e107/commit/7039763bdf89f6e2e7e22047e316ce6c883b5365)
- [forum_viewforum_template.php](https://github.com/rica-carv/e107/commit/94c39dde3c705a58da799a018774c68f190d97c1)

There's also a lot work to be done on the forum_viewforum.php, as it's commented: 
> ///TODO  XXX All these $fVars items need to be put into a shortcode class so they can be parsed with parms and wrappers. Big Job!

**Comment by CaMer0n** [comment]
Unfortunately, this pull-request has conflicts with the existing branch.

**Comment by rica-carv** [comment]
@CaMer0n ??? Anyone doing the same??

**Comment by CaMer0n** [comment]
@rica-carv No, just sync with the latest changes and then resubmit the pull-request. Thanks.

**Pull request closed without merging**
