### PR TITLE
Text to LANS Schedule Tasks (Cron) #6 Added Help

### PR DESCRIPTION
**Pull request by MikeyGMT**
Text to LANS Schedule Tasks (Cron) #6 Added Help

An administrator can automate tasks using e107 Schedule Tasks. [br]
In the Manage Tab, you can edit, delete and run tasks. [br]
When you edit a task you can set the minutes, hours, days, month or day
of the week you want the task to run. Use * to run for each period. Use
the Active property to Enabled the Task.[br]
Note: You are advised not to delete standard jobs.[br]

### CODE REVIEW

**Comment by MikeyGMT** [comment]
Testing 

image

**Comment by MikeyGMT** [comment]
More to do on this one... Please hold.

**Comment by MikeyGMT** [comment]
Removed the bit about using * - as this was incorrect. 

I was going to do some work in cron_class but struggled to test. I'll leave this for another time. 

Should be good to go now.

**Comment by CaMer0n** [comment]
Thank you! 👍

**Pull request merged**
