### PR TITLE
Error page improvement: template support. And status code support for e107::redirect().

### PR DESCRIPTION
**Pull request by lonalore**
kepernyokep_2016-12-14_15-07-40

kepernyokep_2016-12-14_15-07-52

### CODE REVIEW

**Comment by Moc** [comment]
This looks great. Nice code-cleanup. Thanks @lonalore

**Comment by CaMer0n** [comment]
Beautiful work (as usual) ! Thank you! 👍

**Comment by lonalore** [comment]
Thank you! But it is not yet finished. :) I would like to add a method (e.g. e107::setErrorPage()), which can be used for delivering error page contents to the browser directly, without redirect. It would be great for plugin developers to use system error pages in their custom plugins. But I'll need some help from @CaMer0n ... :) I'll send you a message on Gitter.

**Comment by CaMer0n** [comment]
okay! 👍

**Pull request merged**
