### PR TITLE
Update Featurebox English_global.php

### PR DESCRIPTION
**Pull request by yesszus**
Tested and work this!

### CODE REVIEW

**Comment by tgtje** [comment]
Or adding  eg  e107::lan(feauturebox') ...  to **setup** file ???
Above Commit works > what would be prefered way?

**Comment by Jimmi08** [comment]
All 03,04,05 lans needs to move to admin lan file, they are used during installation process too (names of categories)

I am curious about prefered way - like @tgtje asked .

**Comment by CaMer0n** [comment]
Installation terms should NOT be in a `xxxx_global` language file. Global files are for information which may be necessary throughout multiple pages and area of e107.  eg. menu captions, admin navigation etc.  Installation terms are specific to a single page. 
Using `e107::lan() ` inside the setup file is the preferred way.

**Comment by yesszus** [comment]
e107::lan() not work for me!
Added new line and work.

**Comment by CaMer0n** [comment]
All those installation terms should be in the _admin language file (not _global).  e107::lan() won't work on a plugin which isn't installed yet. This is why includeLan() is better in this case.

**Pull request closed without merging**
