### PR TITLE
To avoid cross domain conflict when using https

### PR DESCRIPTION
**Pull request by OTroccaz**

### CODE REVIEW

**Comment by lonalore** [comment]
It would be better to use protocol-relative urls like:

```php
e107::js('url',"//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js");
```

output:
```html
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.1/jquery-ui.min.js"></script>
```

If the browser is viewing that current page in through HTTPS, then it’ll request that asset with the HTTPS protocol, otherwise it’ll typically request it with HTTP.

Technically, this is called a “network-path reference” according to [RFC 3986!](http://tools.ietf.org/html/rfc3986#section-4.2).

**Comment by willem010** [comment]
@lonalore 
that would also solve #805 
perfect!

**Comment by OTroccaz** [comment]
Great, it works!
Thanks.

**Comment by lonalore** [comment]
and also #1183 :)

**Pull request closed without merging**
