### PR TITLE
redefined LANs (install) #6 #1193 (latest)

### PR DESCRIPTION
**Pull request by tgtje**
Amended LAN defines>  third version;  as i found out that NOT all texts inside can carry LANs at certain positions > lines involved  up to 350.(install php)
 (most > die fatal error lines :  'hidden' when 5.3 is running and all is as should. 
Up to that point ( around 350) LANs are not being called ( testcase php 4.*  with added lan's display the lans, not the defines)...(as mentioned hidden if all is correct on newer version of php).

(Note : unsure for LAN 142,143,144 as i can  not access/trigger them)

Not translated are : 
logLines.... are NOT transformed to LAN's (reason : international sharing of logs when errors appear)
template >SetTag..lines .. are NOT transformed to LAN's.
( if i am correct and also above (log/TAG) is ok,, this would be the last revision for install php and language use). 

Second commit : forum  since no reaction and working method #1177 is covered  + update caption/help file

### CODE REVIEW

**Comment by CaMer0n** [comment]
@tgtje Great stuff!! Just a couple of small things to change. 
1) LANINS_131 should be "[x] of [y]" . 
2) We don't make LANs for DEBUG information. so LANINS_143 should be removed.

**Comment by tgtje** [comment]
@CaMer0n  no problem, but point 1 defend  > of is here meant as a common term where the SC's are already set.on their own..

[x] of [y] implements a choice> this is not so . A choice is already preset.

Hard to explain (translated) > example : 2 of a kind  (...of.. needs no explanation, only a translation. Of.here.. does not change ( number is always > 8  ('also' fixed)  )  SC 1 = Step  SC 2=2,3,4,,5,6,7,... OF.... 8
(hence decommented txt > single use) For each language only the 'wording 'is translated to locale, does not have an impact on coding.  Dutch of = van  German of = von  French of = de  Rus of = из  Swed of = af

**Comment by CaMer0n** [comment]
@tgtje Okay, let's leave the [x] of [y] as it is for now. (not sure how it works with right-to-left languages). 

For point 2, only LAN 143 is debug info, the others (142 and 144) are errors. Would you mind fixing that? Then I'll commit this one.. cheers!

**Comment by tgtje** [comment]
*Overworking no point, i will close these commits and **rewrite them again**.* ( i want to update all files to latest so i know i use no older pieces  (to eliminate any errors).
I will remove LAN 143. (def + coding)
As for the [x] of [y]  it (displayed as  install php line 2020 : Installation: {stage_pre} {stage_num} of 8
in changed form >'.LANINS_130.' &#58 {stage_pre} {stage_num} '.LANINS_131.' 8 </.....

Tough one to crack, since it is written by bar (template SetTag) that piece (correct me if i am wrong) would have RTL support already at that stage (lines 1282-1287) to re-arrange the {stage_pre} {stage_num} output  (arabic :  التركيب: الخطوة 3 من 8 )  = loosely 8 of 3 Step :Installation > 8 LANINS_131 {stage num} {step pre} LANINS_130..

**Pull request closed without merging**
