### PR TITLE
Contact Form - Generic Lans #6 and Improved Accessibility Labels #275

### PR DESCRIPTION
**Pull request by MikeyGMT**
Contact Form - Clean Up / Generic Lans #6
Improve Accessible Labels #275 - label tags needed for='formEntityId'
added

### CODE REVIEW

**Comment by MikeyGMT** [comment]
Testing 
image

Improved Wave Accessibility Report
image

http://wave.webaim.org/report#/http://atlantic-apps-online.co.uk/contact.php 

Previously the labels we missing correct "FOR" property. Hence the number of Accessible errors in the contact form has been reduced.

**Comment by CaMer0n** [comment]
Thank you @MikeyGMT !! 👍

**Comment by Moc** [comment]
Good work!

**Comment by Moc** [comment]
LANCONTACT_11 could use some optimisation.

**Pull request merged**
