### PR TITLE
Wrong method mySQLServerInfo (?) in line 3399 gave error on plugin install with mysql dependecies...

### PR DESCRIPTION
**Pull request by rica-carv**
Wrong method mySQLServerInfo (?) in line 3399 gave error on plugin install with mysql dependecies...

imagem

### CODE REVIEW

**Comment by Moc** [comment]
Language files should go in the language pack (e107translations repository)

**Comment by rica-carv** [comment]
> 
> 
> Language files should go in the language pack (e107translations repository).

@moc since portuguese language pack doesn't has the e107_theme, i didn't put it there. Should i?

**Comment by Moc** [comment]
Yes.

**Comment by rica-carv** [comment]
@Moc Done...

**Comment by CaMer0n** [comment]
@rica-carv Thank you.

**Pull request merged**
