### PR TITLE
File Inspector: Update Core Image #1973 and Lans Clean up #6 

### PR DESCRIPTION
**Pull request by MikeyGMT**
File Inspector: Update Core Image #1973 and Lans Clean up #6

### CODE REVIEW

**Comment by MikeyGMT** [comment]
Testing 
image

**Comment by CaMer0n** [comment]
Core-image is auto-generated during release creation. So, it's not expected that core_image will function accurately with the github version of e107.

**Comment by MikeyGMT** [comment]
@CaMer0n oh ok - I did ask. .... never mind. 
You need it reverting as there's LAN updated too.

**Comment by MikeyGMT** [comment]
@CaMer0n I have 2.1.4 Git released 2 days ago, but there are still many non-core files reported - e.g. the "flexpanel" files, but on checking core_image file date, it does not look like it was updated during the release process, as mentioned above.  

image

I am trying to clean up a very old site, hence it's a needle and haystack process :( 

It may be good too, to optionally exclude the system folders, and the old newspost images, i.e. places where users are permitted to upload stuff. 

Thanks
Mikey

**Comment by MikeyGMT** [comment]
Ditto for 2.1.5

**Pull request closed without merging**
