### PR TITLE
Update forum.css

### PR DESCRIPTION
**Pull request by mcpeace-maw**

### CODE REVIEW

**Comment by CaMer0n** [comment]
Because the page is so short, the min-height is prevent the footer of the site appearing halfway up the screen. You should be able to override this with your theme's style.css file.

**Comment by mcpeace-maw** [comment]
I see all from outside, And I think the forum plugin must work out of the box in any theme with no changes. The rgbs colors make that, will work in light and dark themes the same. The imposed min-height I think is not right to be in the plugin, if is needed in a core theme must be added in that core theme,

**Comment by CaMer0n** [comment]
Can you please post a URL to the min-height issue you see?

**Comment by mcpeace-maw** [comment]
http://mcpeace.x10.mx/e1/e107_plugins/forum/forum.php

**Comment by mcpeace-maw** [comment]
With min-height = 500px added in forum.css now I must add in all my themes min-height = 0 to remove the empty space.

**Pull request closed without merging**
