### PR TITLE
plugin.xml

### PR DESCRIPTION
**Pull request by tgtje**
text to LAN issue #6 (name has to be changed, git sees existing file)

### CODE REVIEW

**Comment by CaMer0n** [comment]
Where does this file come from? e107_plugins/user/langupdated_plugin.xml  ?

**Comment by tgtje** [comment]
Github does not allow (why ??)  the same name (plugin.xml). It is the language> LAN adjusted plugin.xml for user plugin.

**Comment by rica-carv** [comment]
You can't change the existing plugin.xml in Github? Weird....

**Comment by Moc** [comment]
@tgtje Try using Github Desktop, it should really help a lot..

**Comment by Moc** [comment]
@tgtje I've fixed this for you now :)

**Comment by tgtje** [comment]
Thanks

**Pull request closed without merging**
