### PR TITLE
Theme Layout improvement - Allow to use "*" wildcard in a path for theme layouts.

### PR DESCRIPTION
**Pull request by lonalore**
kepernyokep_2016-12-01_14-36-52

It works with SEF and Legacy URL too:
- /e107_plugins/[plugin]/project.php
- /project/[user]/[project]
- /project/[user]

### CODE REVIEW

**Comment by rica-carv** [comment]
Humm, maybe with some modifications it could also solve [this](http://e107help.org/2824/how-to-get-real-php-filename-if-sef-urls-are-enabled?show=2982#c2982), since currently i can't enable a menu with SEF urls...

**Comment by lonalore** [comment]
@rica-carv did you try to use `e_URL_LEGACY`? It should also work when SEF URLs are enabled.

```php
if(defset('e_URL_LEGACY') == 'e107_plugins/plugin/file.php')
{
    // Load menu...
}
```

**Comment by rica-carv** [comment]
@lonalore Just tryed.
For some reason, it will only be defined when a page is rendered via SEF url. When a page is rendered via regular url, it's not defined.
The opposite occurs for e_PAGE....
Guess i'll have to end up with both constants, ie:
`If (e_PAGE?:e_URL_LEGACY)...`

**Comment by lonalore** [comment]
I think the best solution would be moving [this Simple URL ReWrite code](https://github.com/e107inc/e107/blob/master/index.php#L60-L160) to `class2.php`. And put a condition after it.

```php
if(!defset('e_URL_LEGACY', false))
{
	define('e_URL_LEGACY', ltrim(e_REQUEST_URI, '/'));
}
```

So, `e_URL_LEGACY` would be available globally, and it would always contain the legacy URL.

**Comment by rica-carv** [comment]
@lonalore Well, for now ended up solving it this way, if it matters:
`$check_url = e_PAGE!="e_PAGE" ? e_PAGE : end(explode('/', parse_url(e_URL_LEGACY)['path']));`

**Comment by CaMer0n** [comment]
@lonalore I'm just checking that you're aware that currently, without your changes, you could just use "project" (as per your example) and it should work for:
-  /project
- /project/something/
- project.php
- e107_plugins/project/something.php 

So I'm not quite seeing the full value of what you've proposed. Can you explain more?

**Comment by lonalore** [comment]
Wow, indeed! It never ever occurred to me to try this. Thank you!

**Pull request closed without merging**
