### PR TITLE
 Feature Request: Forum Link Icon/Image

### PR DESCRIPTION
**Pull request by chory**
Show a image in forum title

### CODE REVIEW

**Comment by rica-carv** [comment]
Can't this be anchieved via template only???
With a theme custom shortcode???

**Comment by chory** [comment]
You can create your own template in your theme, on the route
THEME.'forum_template.php '
or
THEME.'templates / forum / forum_template.php '

**Comment by chory** [comment]
Sorry, I'm going crazy with Github :angry: and I think I created other pull, only for a file https://github.com/chory/e107/commit/fe93f9382087c15fb737bfbdc60902fd574ba3b6

**Comment by Moc** [comment]
@chory 
> THEME.'forum_template.php '
or
THEME.'templates / forum / forum_template.php '

Only the second example. The first one may have been used in v1 but should not be used in v2, it may stop working at some point.

**Comment by rica-carv** [comment]
@chory And what prevents you of using `{FORUMIMG}&nbsp;{FORUMNAME}` on template, instead of `{FORUMIMGTXT}`????
Or even better, why not create `{FORUMNAME}` shortcode with parms???
Like this:
- {FORUMNAME}: renders forum name only (as it is right now)
- {FORUMNAME: image}: renders forum image only
- {FORUMNAME: image&text}: renders forum image + forum name

Just my ideas....

P.S.: On [forum_admin.php, line 148](https://github.com/e107inc/e107/pull/1635/files#diff-c3c86e3037cde314d554bdf96b9cd9a1R148), shouldn't the _title_ inside the array be` 'title' => "Image" `instead of` 'title' => "Imagen" `????
Imagen is spanish for image......
Shouldn't the core database fields be all in English???

**Comment by chory** [comment]
>     {FORUMNAME}: renders forum name only (as it is right now)
>     {FORUMNAME: image}: renders forum image only
>     {FORUMNAME: image&text}: renders forum image + forum name

Yes, it is a good idea, but it is very complex for me

> P.S.: On forum_admin.php, line 148, shouldn't the title inside the array be'title' => "Image"instead of'title' => "Imagen"????

Sorry, but the first thing I do to understand it, and then I forget to translate.
Thanks or notice

**Comment by rica-carv** [comment]
@chory 
> Yes, it is a good idea, but it is very complex for me

Somewhere, sometime in the future, it will have to be donne, as it's commented:

> ///TODO  XXX All these $fVars items need to be put into a shortcode class so they can be parsed with parms and wrappers. Big Job!

@Cameron, couldn't those `$fVars` be replaced by [addScVars](https://github.com/e107inc/e107/blob/8f14ff352729432f400cea2e92aee21d898481e8/e107_handlers/shortcode_handler.php#L1562)???
Something like:
**Original:** 	`$fVars->VIEWABLE_BY = "----shortcode code----";`
**Replacement:** `$sc = e107::getScBatch('-----class_name-----')->addScVars(array('viewable_by', '----shortcode code----'));`
And when template parsing:
**Original:** `$forum_view_end = $tp->simpleParse($FORUM_VIEW_END, $fVars);`
**Replacement:** `$forum_view_end = $tp->simpleParse($FORUM_VIEW_END, $sc);`

**Comment by chory** [comment]
[English]
I thought let alone the shortcode {FORUMIMG}.
Thus, the image can be put anywhere, in front of or behind the text.
And as it is a variable, it is not necessary to call any "function" later, and will be faster execution.
Or so I think.

[Español]
He pensado dejar solo el shortcode {FORUMIMG}.
De esta manera, la imagen se puede poner en cualquier lugar, delante o detras del texto.
Y al tratarse de una variable, no es necesario llamar a ninguna "función", posteriormente, y será más rápida la ejecución.
O eso creo.

**Comment by cameron** [comment]
different @CaMer0n

**Comment by CaMer0n** [comment]
@rica-carv It's possible, but that's the old way. Better we use the shortcode class and get it cleaned up once and for all.  You can check out the vstore plugin for how I'm coding shortcodes these days.

**Comment by rica-carv** [comment]
@chory 
[English]
You got some certain point there, when separating both shortcodes, since you still have the old one as it is, and add a new one, wich can be more flexible on rendering, as you said....
I was just presenting another solution, without have to create a new shortcode....
Regarding the database field addition, i think you can have an image without it, but it will depend of the image manager forum image handler.....
For instance, in v1.4, i have a plugin heavilly using images, and just because keeping database small, i haven't created a filed for the image, instead i rename the image to the unique id of the row....
[Español]
Tienes razón, quando creas otro shortcode separado del original, pues continuas con el antiguo intocable, y añades uno nuevo, que te posibilita colocarlo donde quieras....
Yo estaba solo presentado otra solucion, sin la addicion de un nuevo shortcode....
En aspecto al adicion del campo para la imagen en la base de datos, you creo que podrias tener la imagen sin añadir esse campo, pero eso depende de la forma de manuseamento de las imagenes del forum por parte del media manager....
Por exemplo, yo en v1.4 tengo un plugin que tiene muchas imagenes, y para no aumentar mucho la base de datos, no cree un campo para la imagen. En lugar de eso, yo cambio el nombre de la imagen para corresponder con la ID unica de esa linea de la base de datos....

@CaMer0n Hum, good, i'll give it a look, and if i understand it, i could give a try to get rid of those `$fVars`, can i?

**Comment by chory** [comment]
@rica-carv instead i rename the image to the unique id of the row....
[English]
Yes, that would be fine if the image is hosted on the server itself on a specific route.
But if the image is hosted on a separate server, and do not have control over it, I think it would not be feasible

I will try to implement the shortcode following the example of @ CaMer0n

Thank you very much for your comments, they are being a great help and I bring new ideas.

[Español]
Sí, eso estaría bien si la imagen está alojada en el propio servidor en una ruta específica.
Pero, si esa imagen está alojada en otro servidor independiente, y no se tiene control sobre la misma, yo creo que no sería factible.

Voy a tratar de implementar el shortcode siguiendo el ejemplo de @CaMer0n 

Muchas gracias por vuestros comentarios, me están siendo de gran ayuda y me aportan nuevas ideas.

**Comment by rica-carv** [comment]
@chory 
[English]
I quite understand your problem, but as far i know, right now media manager doesn't allow external images....
Of course, if you can manage to handle the forum images without media manager, it would be possible to use external images...
[Español]
Yo compreendo tu problema, pero segun creo, por ahora media manager no te permite utilizar imagenes alojadas en otro servidor.
Por supuesto, si consigues hacer la gestion de esas imagenes del forum sin el media manager, pues te queda possible hacer eso.

Fuerza con eso...

@CaMer0n I seem to be lost somewhere on your vstore shortcode handling....
You have some shortcodes like this:
`	function sc_cat_info($parm=null)
	{
		return e107::getParser()->toHtml($this->var['cat_info'], true,'BODY');	
	}`
You go fetch the shortcode data to the `$this->var`, right?
Now i'm lost where you define the `$this->vars`.....

**Comment by chory** [comment]
Well, some time later, and in a moment of inspiration (this does not create precedent), I have managed to do what I wanted, if, and with shortcodes.
I have created two new shortcodes, PARENTIMG and FORUMIMG, that support the parameters w = width, h = height, crop = crop image (1 or 0), fmt = format, the latter can be specified if the text (txt) or image (img) is desired in any Order for example
Fmt = txt would only display text
Fmt = img would only display the image
Fmt = imgtxt would display the image and to its right the text
Fmt = img <=> txt would display the image and to your right the text separated by <=>

If you think it works well, I think you could modify the shortcodes, PARENTNAME and FORUMNAME, to accept those parameters and return the corresponding data, thus eliminating the shortcodes PARENTIMG and FORUMIMG.

Now to see if I remember how it made me to send you the code 😉

**Pull request closed without merging**
