### PR TITLE
Possible patch for issue #2369

### PR DESCRIPTION
**Pull request by rica-carv**
Possible patch for issue #2369

### CODE REVIEW

**Comment by CaMer0n** [comment]
Please try with my last commit. eg. 

    $parms = $tmp->getParams('news_months_menu', 2); // area 2

**Comment by rica-carv** [comment]
@CaMer0n Your last commit works, but forces a plugin writer to know in which menuarea is the menu activated...
A bit odd, no?
Furthermore, even in a menuarea that only has a menu ([MENU=loginmenu}, it's needed to call the new getParams function, even inside the menu itself, so a menu coder needs to call it, in order to prevent if the menu could be activated in a single named menu area... Is this good practice?

My commit makes the params from the menu database directly available (if they're present, beware #2400...) to those menuareas during code run, without the need to call another function....

**Comment by CaMer0n** [comment]
There's 2 different ways of rendering menus.. and you're mixing them, which isn't an intended feature.
You're choices are like this: 

1) Use Menu-Manager, assign your prefs in there (e_menu)  and assign the menu placement in there. 
OR
2) Hard-code your menu and assign your prefs in the shortcode. eg. {MENU: path=loginmenu&limit=3.etc.etc...}

It sounds like what you're trying to do is take the prefs from #1 and render them like #2 with the hardcoded prefs omitted. I don't encourage that.

**Comment by rica-carv** [comment]
@CaMer0n So, since a hard-coded menu can't have admin ui managed parms, a theme designer will have to know which parms a menu needs and hardcode them in a single hardcoded area, right?
A admin will not have any control in those menu parms (unless it edits the theme itself)....
It's kind of odd, no?
A admin can control the parms of menus in menu areas via admin ui but cannot control the parms of a hardcoded menu via admin ui....
Isn't it possible for menu manager to handle also the hardcoded menus parms?

Somehow, i get your point, since hardcoded menus are theme related, but as i see it, it's parms are not, since they are somehow defined by default in menu config files inside the plugin folder...

**Comment by rica-carv** [comment]
Can i have a feedback with this was closed without merging? Thanks.

**Pull request closed without merging**
