### PR TITLE
Refactoring for Cron Scheduler.

### PR DESCRIPTION
**Pull request by lonalore**
Tested on e107projects.com. It works fine.

### CODE REVIEW

**Comment by CaMer0n** [comment]
Thank you @lonalore !!

**Comment by CaMer0n** [comment]
I upgraded e107.org and the cron jobs stopped functioning directly after that. Reverted this commit and they began again. Please re-submit after more testing. Thanks!

**Comment by lonalore** [comment]
How do you call cron.php? Do you use wget, curl, lynx or you run PHP as a CGI?

**Comment by lonalore** [comment]
I did some tests on my debian based development environment:

**wget** (Tested, it works)
`/usr/bin/wget -O - -q http://e107.dev/cron.php?token=TOKEN > /dev/null 2>&1`

**curl** (Tested, it works)
`/usr/bin/curl --silent --compressed http://e107.dev/cron.php?token=TOKEN > /dev/null 2>&1`

**lynx** (Tested, it works)
`/usr/bin/lynx -source http://e107.dev/cron.php?token=TOKEN > /dev/null 2>&1`

**PHP** (Tested, it works)
`/usr/bin/php /var/www/drupalvm/e107.dev/web/cron.php token=TOKEN`

And it also works on my VPS (crontab is managed by IspConfig) and on a hungarian webhosting (crontab is managed by cPanel).

**Comment by CaMer0n** [comment]
Thank you @lonalore 

`token=` is a more recent addition, the older method used arguments. 
Called via cPanel's Cron job, it looks similar to this: 

`/public_html/cron.php 289e8c3ae39aa5ee11535fca26d24294bc018cd0`

**Comment by lonalore** [comment]
You can use it without `token=` too. It uses `str_replace('token=', '', $pwd);` I didn't change that code:

[Old code](https://github.com/e107inc/e107/blob/master/cron.php#L33-L42) vs [New code](https://github.com/lonalore/e107/blob/cron/e107_handlers/cron_class.php#L1141-L1150)... no differences. :)

So, `/public_html/cron.php 289e8c3ae39aa5ee11535fca26d24294bc018cd0` should work too. Please check your file permission.

**Comment by lonalore** [comment]
No, it doesn't. The permission is 644 on my cron_class.php, and it works. I have no idea. :/ 
I will try to do more tests on this week.
Thank you!

**Comment by lonalore** [comment]
I might know what the problem is. As you mentioned, you run the cron using the following command:
```
/public_html/cron.php 289e8c3ae39aa5ee11535fca26d24294bc018cd0
```
But in this case, you attempt to run `cron.php` as a **shebang** script. It worked before my changes because of [this line](https://github.com/e107inc/e107/blob/master/cron.php#L1).

But I removed it, because it's path specificand it's only supported by UNIX based systems, and it does not work for example on Windows servers.

Please change your command to the command below, then try to run your cron again:
```
/usr/bin/php /public_html/cron.php 289e8c3ae39aa5ee11535fca26d24294bc018cd0
```

If we really want to support running cron as a UNIX shell script, then we should create a **cron.sh** file instead of mixing the PHP and shell script. For example:

```bash
#!/usr/bin/env php
<?php
include 'cron.php';
```

**Comment by CaMer0n** [comment]
For sure it is due to the shebang removal. I don't think it is a good idea to remove it, and then have to ask everyone who has crons configured on all their sites to update all their cron configurations.  Windows is not officially supported, while the majority are using Unix based systems, so rather than modifying what works for Unix already, perhaps a plugin can be made to support Windows systems if that's what you need?.

**Comment by lonalore** [comment]
I put the shebang line back to the code. I'll create a new pull-request.

**Pull request merged**
