### PR TITLE
Breadcrumb HTML in code removal 

### PR DESCRIPTION
**Pull request by rica-carv**
Breadcrumb PHP in code HTML removal & moved to theme.php (or should it have a template file of it's own?)

### CODE REVIEW

**Comment by CaMer0n** [comment]
Sorry @rica-carv . Not liking this. Seems like overkill, especially since it is just following bootstrap standards. What it is that you are trying to do via a custom template?

**Comment by rica-carv** [comment]
@CaMer0n I'm trying to do this: http://bootsnipp.com/snippets/featured/triangle-breadcrumbs-arrows
But with hardcoded "bootstrap" html inside it, it's kind of hard to just do it via css rules.
Bootstrap allows a lot of customization, some still responsive, but with hardcoded html as this, it's kind of hard to customize....
If you have any other ideia....

**Comment by CaMer0n** [comment]
> But with hardcoded "bootstrap" html inside it, it's kind of hard to just do it via css rules.

No, it's possible. This does the same thing. And if you needed different colors, you could wrap the breadcrumb in a container. eg . <`div class='breadcrumb-blue'>{BREADCRUMB}</div>`

    ul.breadcrumb { 
			list-style: none; 
			overflow: hidden; 
                    padding:0;
		}
		ul.breadcrumb li { 
			float: left; 
		}
		ul.breadcrumb a {
			color: white;
			text-decoration: none; 
			padding: 10px 0 10px 55px;
			/*! background: brown; */                   /* fallback color */
			background: #ED9C28; 
			position: relative; 
			display: block;
			float: left;
		}
		ul.breadcrumb li a:after { 
			content: " "; 
			display: block; 
			width: 0; 
			height: 0;
			border-top: 50px solid transparent;           /* Go big on the size, and let overflow hide */
			border-bottom: 50px solid transparent;
			border-left: 30px solid #ED9C28;
			position: absolute;
			top: 50%;
			margin-top: -50px; 
			left: 100%;
			z-index: 2; 
		}	
		ul.breadcrumb li a:before { 
			content: " "; 
			display: block; 
			width: 0; 
			height: 0;
			border-top: 50px solid transparent;           /* Go big on the size, and let overflow hide */
			border-bottom: 50px solid transparent;
			border-left: 30px solid white;
			position: absolute;
			top: 50%;
			margin-top: -50px; 
			margin-left: 1px;
			left: 100%;
			z-index: 1; 
		}	
		ul.breadcrumb li:first-child a {
			padding-left: 10px;
		}

		ul.breadcrumb li     {color: #fff; background-color: #ED9C28  }
		ul.breadcrumb li a:after { border-left-color: #ED9C28; }

	
		ul.breadcrumb li a:hover { background: hsla(34,85%,25%,1); }
		ul.breadcrumb li a:hover:after { border-left-color: hsla(34,85%,25%,1) !important; }

**Comment by rica-carv** [comment]
@CaMer0n Thanks. Almost, but it's not quite exactly the same.
Notice the missing borders (wich are rendered as a bootstrap btn class)...
breadcrumb

button-groups

**Comment by rica-carv** [comment]
Forget it, solved it....

**Pull request closed without merging**
