### PR TITLE
Update jquery to v3.1.1

### PR DESCRIPTION
**Pull request by rica-carv**
Update jquery to v3.1.1

### CODE REVIEW

**Comment by CaMer0n** [comment]
Thanks @lonalore is working on something for this, bootstrap and other libraries. This is why I am holding off on these merges.

**Comment by lonalore** [comment]
@CaMer0n merged my changes yesterday, so now, you can use newer versions of jQuery, Bootstrap... etc easily. Here is an example how you can achieve it: https://gist.github.com/lonalore/a7c1d5aee0e7821dba03cb8ab5dfdefa

**Comment by CaMer0n** [comment]
Now conflicting.

**Comment by CaMer0n** [comment]
Closing. Solution in the comments.

**Pull request closed without merging**
