### PR TITLE
Removed Google+

### PR DESCRIPTION
**Pull request by LaocheXe**
Removed Google+ since it is shutdown.

### CODE REVIEW

**Comment by LaocheXe** [comment]
Google+ has shut down, making this useless social link.

**Comment by net1313** [comment]
Google+ is dead, but if you want to keep social plugin update and allow users login/register through Google account (eg. gmail) just replace a file Google.php in Providers directory of Hybridauth by this file
(https://github.com/hybridauth/hybridauth/blob/e7fb724aea4822b48e6d484e58ac8e541b205086/hybridauth/Hybrid/Providers/Google.php)
was successfully tested and works.

**Comment by LaocheXe** [comment]
This just removed the options to add Google+ Profile/group link to be displayed on the frontend - has nothing to do with social login

**Comment by CaMer0n** [comment]
Thanks @LaocheXe ! :+1:

**Pull request merged**
