### PR TITLE
The e_parse_class::toForm() didn't convert &039; back to '

### PR DESCRIPTION
**Pull request by SimSync**
see also https://github.com/e107inc/e107-test/pull/12

### CODE REVIEW

**Comment by CaMer0n** [comment]
Are you sure this is not deliberate? I imagine HTML inside single quotes could break?

ie. `$text = '<textarea>'.$tp->toForm($db_html).'</textarea>' `

Also, I'm not aware of any 'bug symptoms' associated with this very old method. Are you?

**Comment by SimSync** [comment]
I don't have issues with it, except:
This came up due to your `testToForm()` method, because the `toDB()` method used there, converts `'` to `&039;`, but `toForm()` doesn't convert the converted string back to it's original (if it's not surrounded by `[html][/html]`).

**Comment by CaMer0n** [comment]
Thanks. Let's hold off for now.

**Comment by SimSync** [comment]
I thought once again about it and my expectation was wrong.
I expected to get the same string back that was given as input. But the `toForm()` method prepares the string to be used in form controls, not to return the original "raw" string that was entered by the user.
To get the raw input, i think i would have to use `html_entity_decode()` or `htmlspecialchars_decode()`.
So, that means my change on `toForm()` is wrong and the expected string should be with `&039;` instead of `'`.
I close this PR for now.

**Comment by CaMer0n** [comment]
:+1:

**Pull request closed without merging**
