### PR TITLE
Language use for plugin Social, and XUP LAN's

### PR DESCRIPTION
**Pull request by tgtje**
Social plugin language use,
Messages for Xup etc

### CODE REVIEW

**Comment by CaMer0n** [comment]
Thank you @tgtje !!  - just a small change needed - we should never split a sentence into 2 LANS. eg. LAN_XUP_SIGNUP." {$p} ".LAN_XUP_SIGNUPb. (and never use lowercase. eg. 'b')

Instead we would use one LAN with [x] and then replace [x] with $p. 
eg. "Register using your [x] account".

**Comment by tgtje** [comment]
Sorry ; maybe i do not get all that is needed to accomplish it (as mentioned before, i am not that good with coding). After 3 hours of experimenting (str replace/arrays) i decide NOT to assign that line to a LAN. I just do not get what to do to get it function properly. > alternative

how about this as LAN : 

> define("LAN_XUP_SIGNUP", "Sign-in with your account");
and as code : 

> $text .= " <a title=' {$p} : ". LAN_XUP_SIGNUP." ' role='button' class='signup-xup  btn btn-primary' href='".e107::g....................   (both for button and text)

It will display in the end as user as > ex :    facebook : Sign in with your account.

**Comment by Moc** [comment]
@tgtje Maybe something like this:

From;
`title='Register using your {$p} account'`

To
`title='".str_replace("[x]", $p, LAN_XUP_REG)."'`

With 
`define("LAN_XUP_REG", "Register using your [x] account");`

**Comment by tgtje** [comment]
Thank you , i just saw with this example what i did wrong..

It works doing it this way :-)

---
Dit e-mailbericht is gecontroleerd op virussen met Avast antivirussoftware.
https://www.avast.com/antivirus

**Comment by Moc** [comment]
Haha I thought I was quick enough. 

Use the lanVars method. They're essentially the same in this basic scenario but the lanVars method allows for easy customization in the future.

**Comment by tgtje** [comment]
Thank you, will do

**Comment by tgtje** [comment]
new pull created (amend version)

**Pull request closed without merging**
