### PR TITLE
Update e107_admin/db.php

### PR DESCRIPTION
**Pull request by yesszus**
Add pharses

### CODE REVIEW

**Comment by CaMer0n** [comment]
Thank you @yesszus !! Just a small change needed here. Line 423. 

    $message = DBLAN_121. $oldPath. DBLAN_122. $newPath;

should be: 

    $message-> e107::getParser()->lanVars(DBLAN_121, array('x'=>$oldPath, 'y'=>$newPath)); 

and.. in the language file... 

    define("DBLAN_121", "Moving [x] to [y]."); 

(DBLAN_122 can be replaced with something else)

**Comment by yesszus** [comment]
This code line not work, i see a white screen:
`$message-> e107::getParser()->lanVars(DBLAN_121, array('x'=>$oldPath, 'y'=>$newPath));`

This work for me without error:
`$message = DBLAN_121. $oldPath. DBLAN_122. $newPath;`

**Comment by Moc** [comment]
It should be 
$message = e107::getParser()->lanVars(DBLAN_121, array('x'=>$oldPath, 'y'=>$newPath));

**Comment by yesszus** [comment]
Big thks Moc!
This perfect code line!

**Pull request merged**
